export type FieldType =
  | "text"
  | "number"
  | "currency"
  | "date"
  | "select"
  | "textarea"
  | "url"
  | "email";

export type ModuleField = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: string[];
  placeholder?: string;
  help?: string;
  wide?: boolean;
  aliases?: string[];
};

export type ModuleDefinition = {
  id: string;
  label: string;
  shortLabel: string;
  eyebrow: string;
  description: string;
  color: string;
  lightColor: string;
  titleField: string;
  referenceField: string;
  statusField: string;
  dateField: string;
  amountField: string;
  spreadsheetSheets: string[];
  fields: ModuleField[];
  tableColumns: string[];
};

const statusFinanceiro = [
  "Pendente",
  "Aguardando aprovação",
  "Aprovado",
  "Vence em 7 dias",
  "Vencido",
  "Pago",
  "Reprovado",
  "Cancelado",
];

export const moduleDefinitions: ModuleDefinition[] = [
  {
    id: "works",
    label: "Execução da Obra e Produtividade",
    shortLabel: "Execução da Obra",
    eyebrow: "Controle executivo",
    description:
      "Avanço físico, produtividade, equipe própria e disponibilidade das máquinas por obra.",
    color: "#2563eb",
    lightColor: "#eff6ff",
    titleField: "name",
    referenceField: "code",
    statusField: "status",
    dateField: "startDate",
    amountField: "budget",
    spreadsheetSheets: ["02_OBRAS"],
    tableColumns: [
      "code",
      "name",
      "currentStage",
      "physicalProgress",
      "plannedProgress",
      "manager",
      "status",
    ],
    fields: [
      { key: "code", label: "Código da obra", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["Código obra"] },
      { key: "cno", label: "Inscrição CNO", type: "text", help: "Número oficial da obra no Cadastro Nacional de Obras. A consulta oficial exige acesso autorizado ao e-CAC.", aliases: ["CNO"] },
      { key: "cei", label: "Matrícula CEI anterior", type: "text", help: "Preencha somente quando houver cadastro legado migrado para CNO.", aliases: ["CEI"] },
      { key: "name", label: "Nome da obra", type: "text", required: true, placeholder: "Ex.: Reforma da Unidade Salvador", aliases: ["Nome da obra"] },
      { key: "client", label: "Cliente", type: "text", placeholder: "Nome do contratante", aliases: ["Cliente"] },
      { key: "constructionType", label: "Tipo de obra", type: "select", options: ["Edificação", "Reforma", "Demolição", "Obra de infraestrutura", "Serviço especializado", "Outro"] },
      { key: "city", label: "Cidade e estado", type: "text", placeholder: "Ex.: Salvador/BA", aliases: ["Cidade/UF"] },
      { key: "costCenter", label: "Centro de custo", type: "text", placeholder: "Ex.: CC-Obra Salvador", help: "Nome ou código usado pelo financeiro para separar os gastos desta obra.", aliases: ["Centro de custo"] },
      { key: "manager", label: "Gestor responsável", type: "text", aliases: ["Gestor"] },
      { key: "foreman", label: "Encarregado da obra", type: "text", aliases: ["Encarregado"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Ativa", "Planejada", "Pausada", "Concluída"], aliases: ["Status"] },
      { key: "startDate", label: "Início", type: "date", aliases: ["Início"] },
      { key: "endDate", label: "Previsão de término", type: "date", aliases: ["Previsão fim"] },
      { key: "budget", label: "Orçamento de referência", type: "currency", aliases: ["Orçamento referência"] },
      { key: "realizedCost", label: "Custo realizado acumulado", type: "currency", help: "Total efetivamente apropriado na obra até a última atualização gerencial." },
      { key: "openCommitments", label: "Compromissos financeiros em aberto", type: "currency", help: "Contratos, pedidos e obrigações já assumidos que ainda não foram realizados ou pagos integralmente." },
      { key: "estimatedCostToComplete", label: "Estimativa restante para concluir", type: "currency", help: "Valor gerencial ainda necessário para finalizar a obra. Inclua aqui os compromissos em aberto para não subestimar a necessidade." },
      { key: "plannedProgress", label: "Avanço planejado até hoje (%)", type: "number", help: "Percentual previsto na linha de base do cronograma para a data da atualização." },
      { key: "physicalProgress", label: "Avanço físico executado (%)", type: "number", help: "Percentual gerencial comprovado pela engenharia; não substitui a medição formal." },
      { key: "scheduleDelayDays", label: "Atraso apurado pela linha de base (dias)", type: "number", help: "Informe os dias de atraso apurados pelo planejamento, pela Curva S ou pelo cronograma-base. Não converta automaticamente a diferença percentual em dias." },
      { key: "dailyWorkHours", label: "Jornada operacional considerada (h/dia)", type: "number", help: "Usada apenas para converter horas improdutivas em dias equivalentes. Na ausência de informação, o painel considera 8 horas." },
      { key: "currentStage", label: "Etapa atual da obra", type: "select", options: ["Mobilização", "Terraplenagem", "Fundações", "Estrutura", "Alvenaria", "Cobertura", "Instalações", "Acabamentos", "Comissionamento", "Entrega", "Outro"] },
      { key: "currentStageProgress", label: "Avanço da etapa atual (%)", type: "number", help: "Percentual executado dentro da etapa atual, separado do avanço físico total da obra." },
      { key: "currentProcess", label: "Processo em execução agora", type: "textarea", wide: true, placeholder: "Ex.: elevação das paredes dos apartamentos 101 a 104 do bloco A" },
      { key: "currentScope", label: "O que está sendo construído agora", type: "textarea", wide: true, placeholder: "Ex.: elevação das paredes do 2º pavimento e passagem das tubulações elétricas" },
      { key: "totalPlannedDays", label: "Prazo total planejado (dias)", type: "number" },
      { key: "ownTeamProgress", label: "Execução da equipe própria (%)", type: "number", help: "Avanço das frentes sob responsabilidade direta da equipe interna." },
      { key: "requiredOwnTeamCount", label: "Equipe própria necessária na etapa", type: "number", help: "Quantidade de pessoas próprias necessárias para operar a etapa atual em 100%. O painel compara este número com a equipe mobilizada no último diário validado." },
      { key: "nextMilestone", label: "Próximo marco da obra", type: "text", placeholder: "Ex.: concluir laje do 2º pavimento" },
      { key: "nextMilestoneDate", label: "Data prevista do próximo marco", type: "date" },
      { key: "riskLevel", label: "Nível de atenção", type: "select", options: ["Normal", "Atenção", "Crítico"] },
      { key: "scheduleNotes", label: "Desvios e plano de recuperação", type: "textarea", wide: true },
      { key: "cnoStatus", label: "Situação do CNO", type: "select", options: ["Não informado", "A inscrever", "Ativo", "Paralisado", "Reativado", "Encerrado", "Em conferência"] },
      { key: "cnoResponsible", label: "Responsável perante o CNO", type: "text" },
      { key: "cnoLastValidation", label: "Última conferência no CNO", type: "date" },
      { key: "taxLotation", label: "Lotação tributária / FPAS da obra", type: "text", placeholder: "Ex.: código da lotação utilizado no eSocial" },
      { key: "cprbMode", label: "Tratamento previdenciário da obra", type: "select", options: ["A parametrizar", "Folha", "CPRB / desoneração", "Regime misto", "Não aplicável"], help: "A seleção deve ser validada pela contabilidade conforme CNAE, período e contrato." },
      { key: "channel", label: "Canal ou e-mail da obra", type: "text", placeholder: "Ex.: equipe.salvador@empresa.com.br", aliases: ["Canal/e-mail"] },
      { key: "dailyLogUrl", label: "Diário de obra digital", type: "url", placeholder: "Cole o link do diário de obra no SharePoint ou sistema técnico" },
      { key: "documentsUrl", label: "Pasta de documentos", type: "url", placeholder: "Cole o link do SharePoint ou OneDrive", help: "Use o endereço da pasta onde ficam contratos, fotos e documentos da obra.", aliases: ["Link documentos"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "contractors",
    label: "Registro de Terceiros",
    shortLabel: "Registro de Terceiros",
    eyebrow: "Contratos • Serviços terceirizados",
    description:
      "Terceiros contratados, atividade executada, trabalhadores envolvidos, valores, documentos e aprovação.",
    color: "#8a4b08",
    lightColor: "#fff8e8",
    titleField: "companyName",
    referenceField: "measurementId",
    statusField: "status",
    dateField: "measurementDate",
    amountField: "measuredAmount",
    spreadsheetSheets: [],
    tableColumns: ["measurementId", "companyName", "service", "workerCount", "measurementDate", "measuredAmount", "status"],
    fields: [
      { key: "measurementId", label: "Código do registro", type: "text", required: true, help: "Identificador único do terceiro e do acompanhamento do serviço." },
      { key: "companyName", label: "Razão social / nome do terceiro", type: "text", required: true },
      { key: "cnpj", label: "CPF ou CNPJ", type: "text", required: true },
      { key: "workCode", label: "Código da obra", type: "text", placeholder: "Ex.: OBRA-2026-001" },
      { key: "work", label: "Obra vinculada", type: "text", required: true },
      { key: "cno", label: "CNO relacionado (opcional)", type: "text" },
      { key: "contractNumber", label: "Número do contrato", type: "text" },
      { key: "service", label: "Serviço / atividade executada", type: "text", required: true, placeholder: "Ex.: execução de alvenaria" },
      { key: "currentActivity", label: "O que o terceiro está executando agora", type: "textarea", wide: true },
      { key: "workerCount", label: "Trabalhadores terceirizados na atividade", type: "number", required: true, placeholder: "Ex.: 8", help: "Informe quantas pessoas do terceiro estão exercendo esta atividade." },
      { key: "contractValue", label: "Valor total do contrato", type: "currency" },
      { key: "scopeWeight", label: "Peso do escopo no avanço da obra (%)", type: "number", help: "Quanto este contrato representa no avanço físico total da obra." },
      { key: "plannedProgress", label: "Execução planejada do terceiro (%)", type: "number" },
      { key: "executionProgress", label: "Execução comprovada do terceiro (%)", type: "number", help: "Percentual acumulado do escopo contratado, validado pela engenharia." },
      { key: "productivityStatus", label: "Condição da frente terceirizada", type: "select", options: ["No ritmo", "Atenção", "Atrasada", "Paralisada", "Concluída"] },
      { key: "delayReason", label: "Motivo do desvio ou paralisação", type: "text" },
      { key: "expectedCompletion", label: "Previsão de conclusão do escopo", type: "date" },
      { key: "lastProgressUpdate", label: "Última atualização do avanço", type: "date" },
      { key: "measurementNumber", label: "Etapa / número da medição", type: "text" },
      { key: "measurementDate", label: "Data da conferência do serviço", type: "date", required: true },
      { key: "measuredAmount", label: "Valor do serviço realizado", type: "currency", required: true },
      { key: "retentionInss", label: "Retenção previdenciária (R$)", type: "currency", help: "Informe o valor apurado; a incidência e a alíquota dependem do serviço e devem ser validadas." },
      { key: "retentionIss", label: "Retenção de ISS (R$)", type: "currency", help: "Informe o valor apurado conforme o município e a natureza do serviço." },
      { key: "netAmount", label: "Valor líquido a pagar", type: "currency" },
      { key: "status", label: "Situação do serviço / pagamento", type: "select", required: true, options: ["Rascunho", "Em conferência", "Aguardando aprovação", "Aprovada", "Faturada", "Paga", "Rejeitada"] },
      { key: "invoiceUrl", label: "Nota fiscal / fatura", type: "url" },
      { key: "measurementUrl", label: "Relatório / comprovante do serviço", type: "url" },
      { key: "contractUrl", label: "Contrato e aditivos", type: "url" },
      { key: "responsible", label: "Responsável pela conferência", type: "text" },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "worklogs",
    label: "Diário de produtividade da obra",
    shortLabel: "Diário de obra",
    eyebrow: "Engenharia • Produção diária",
    description:
      "Registro diário da atividade executada, avanço físico, equipe própria, horas perdidas e causas de improdutividade.",
    color: "#0f766e",
    lightColor: "#ecfdf5",
    titleField: "currentActivity",
    referenceField: "logId",
    statusField: "status",
    dateField: "date",
    amountField: "",
    spreadsheetSheets: [],
    tableColumns: [
      "date",
      "work",
      "currentStage",
      "productivityStatus",
      "lostHours",
      "progressPercentAfter",
      "status",
    ],
    fields: [
      { key: "logId", label: "Código do diário", type: "text", required: true, help: "Identificador único gerado pelo sistema." },
      { key: "workCode", label: "Código da obra", type: "text", required: true },
      { key: "work", label: "Obra", type: "text", required: true },
      { key: "date", label: "Data do apontamento", type: "date", required: true },
      { key: "shift", label: "Turno", type: "select", options: ["Integral", "Manhã", "Tarde", "Noite"] },
      { key: "currentStage", label: "Etapa da obra", type: "select", required: true, options: ["Mobilização", "Terraplenagem", "Fundações", "Estrutura", "Alvenaria", "Cobertura", "Instalações", "Acabamentos", "Comissionamento", "Entrega", "Outro"] },
      { key: "currentActivity", label: "O que foi construído ou executado", type: "textarea", required: true, wide: true, placeholder: "Descreva a frente, o local e a quantidade executada." },
      { key: "productivityStatus", label: "Condição do dia", type: "select", required: true, options: ["Produtivo", "Parcialmente improdutivo", "Improdutivo"] },
      { key: "lostHours", label: "Horas de paralisação da frente", type: "number", help: "Informe o tempo produtivo perdido no dia, sem multiplicar pela quantidade de trabalhadores. O painel converte as horas em dias conforme a jornada cadastrada na obra." },
      { key: "unproductiveCause", label: "Causa principal da improdutividade", type: "select", options: ["Não se aplica", "Chuva", "Maquinário quebrado", "Operador ausente", "Falta de material", "Aguardando liberação", "Segurança / interdição", "Falta de energia", "Acesso / logística", "Outro"] },
      { key: "conditionDetail", label: "Condição e impacto observado", type: "textarea", wide: true, placeholder: "Ex.: chuva forte entre 08h e 14h impediu concretagem da laje." },
      { key: "affectedEquipment", label: "Máquina ou equipamento afetado", type: "text" },
      { key: "absentOperator", label: "Função ou operador ausente", type: "text" },
      { key: "ownTeamCount", label: "Equipe própria mobilizada", type: "number" },
      { key: "progressDelta", label: "Avanço produzido no dia (p.p.)", type: "number", help: "Incremento em pontos percentuais produzido neste apontamento." },
      { key: "progressPercentAfter", label: "Avanço físico acumulado após o dia (%)", type: "number" },
      { key: "weatherCondition", label: "Condição climática", type: "select", options: ["Ensolarado", "Nublado", "Chuva leve", "Chuva forte", "Vento forte", "Não informado"] },
      { key: "evidenceUrl", label: "Fotos, relatório ou evidência", type: "url" },
      { key: "responsible", label: "Responsável pelo apontamento", type: "text", required: true },
      { key: "status", label: "Situação do diário", type: "select", required: true, options: ["Rascunho", "Enviado", "Validado", "Correção solicitada"] },
      { key: "notes", label: "Observações adicionais", type: "textarea", wide: true },
    ],
  },
  {
    id: "suppliers",
    label: "Fornecedores",
    shortLabel: "Fornecedores",
    eyebrow: "Cadastro-base",
    description:
      "Cadastro, validade documental e situação dos fornecedores utilizados pela empresa.",
    color: "#0f766e",
    lightColor: "#ecfdf5",
    titleField: "companyName",
    referenceField: "code",
    statusField: "status",
    dateField: "documentValidity",
    amountField: "",
    spreadsheetSheets: ["04_FORNECEDORES"],
    tableColumns: ["code", "companyName", "category", "city", "status"],
    fields: [
      { key: "code", label: "Código do fornecedor", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["Código fornecedor"] },
      { key: "cnpj", label: "CNPJ", type: "text", aliases: ["CNPJ"] },
      { key: "companyName", label: "Razão social", type: "text", required: true, aliases: ["Razão social"] },
      { key: "tradeName", label: "Nome fantasia", type: "text", aliases: ["Nome fantasia"] },
      { key: "category", label: "O que fornece", type: "text", placeholder: "Ex.: material elétrico, locação ou alimentação", aliases: ["Categoria"] },
      { key: "contact", label: "Pessoa de contato", type: "text", aliases: ["Contato"] },
      { key: "phone", label: "Telefone", type: "text", aliases: ["Telefone"] },
      { key: "email", label: "E-mail", type: "email", aliases: ["E-mail"] },
      { key: "city", label: "Cidade/UF", type: "text", aliases: ["Cidade/UF"] },
      { key: "bankValidated", label: "Dados bancários conferidos?", type: "select", options: ["Sim", "Não", "Em validação"], help: "Confirma se os dados para pagamento foram verificados com o fornecedor.", aliases: ["Banco validado?"] },
      { key: "documentValidity", label: "Validade dos documentos", type: "date", aliases: ["Validade documentos"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Ativo", "Em validação", "Bloqueado", "Inativo"], aliases: ["Status"] },
      { key: "rating", label: "Avaliação do fornecedor (1 a 5)", type: "number", help: "1 significa ruim e 5 significa excelente.", aliases: ["Avaliação (1-5)"] },
      { key: "documentsUrl", label: "Pasta de documentos", type: "url", placeholder: "Cole o link do SharePoint ou OneDrive", aliases: ["Link documentos"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "expenses",
    label: "Contas a pagar",
    shortLabel: "Contas a pagar",
    eyebrow: "Financeiro",
    description:
      "Contas a pagar, fornecedores, vencimentos, aprovações e links das notas fiscais.",
    color: "#17324d",
    lightColor: "#edf4f8",
    titleField: "description",
    referenceField: "accountId",
    statusField: "status",
    dateField: "dueDate",
    amountField: "expectedAmount",
    spreadsheetSheets: ["05_CONTAS_PAGAR"],
    tableColumns: ["accountId", "supplier", "description", "dueDate", "expectedAmount", "status", "invoiceUrl"],
    fields: [
      { key: "accountId", label: "Código do pagamento", type: "text", required: true, help: "Criado automaticamente. Não é número de conta bancária.", aliases: ["ID conta"] },
      { key: "supplierCode", label: "Código interno do fornecedor", type: "text", help: "Opcional. Use apenas se a empresa já trabalhar com códigos de fornecedores.", aliases: ["Código fornecedor"] },
      { key: "supplier", label: "Fornecedor", type: "text", required: true, aliases: ["Fornecedor"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "costCenter", label: "Centro de custo", type: "text", help: "Indica em qual obra ou área este gasto será contabilizado.", aliases: ["Centro de custo"] },
      { key: "category", label: "Tipo de gasto", type: "text", placeholder: "Ex.: material, aluguel, manutenção", aliases: ["Categoria"] },
      { key: "description", label: "O que será pago?", type: "text", required: true, placeholder: "Ex.: Compra de cimento e areia", aliases: ["Descrição"] },
      { key: "issueDate", label: "Data da nota ou cobrança", type: "date", aliases: ["Emissão"] },
      { key: "dueDate", label: "Vencimento", type: "date", required: true, aliases: ["Vencimento"] },
      { key: "expectedAmount", label: "Valor a pagar", type: "currency", required: true, aliases: ["Valor previsto"] },
      { key: "approval", label: "Situação da aprovação", type: "select", options: ["Pendente", "Aprovada", "Devolvida", "Rejeitada"], help: "Mostra se um responsável já autorizou o pagamento.", aliases: ["Aprovação"] },
      { key: "status", label: "Status do pagamento", type: "select", required: true, options: statusFinanceiro, aliases: ["Status pagamento"] },
      { key: "paymentDate", label: "Data do pagamento", type: "date", aliases: ["Data pagamento"] },
      { key: "paidAmount", label: "Valor pago", type: "currency", aliases: ["Valor pago"] },
      { key: "invoiceUrl", label: "Nota fiscal ou cobrança", type: "url", placeholder: "Cole o link do arquivo", help: "Informe o link da nota fiscal, boleto ou fatura salvo no SharePoint/OneDrive.", aliases: ["Link nota/fatura", "Link nota", "Documento fiscal"] },
      { key: "receiptUrl", label: "Comprovante de pagamento", type: "url", placeholder: "Cole o link do comprovante", aliases: ["Link comprovante"] },
      { key: "responsible", label: "Responsável pelo lançamento", type: "text", aliases: ["Responsável"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "cards",
    label: "Cartões corporativos",
    shortLabel: "Cartões",
    eyebrow: "Financeiro",
    description:
      "Despesas por titular, cartão, obra, estabelecimento, aprovação e documento fiscal.",
    color: "#7c3aed",
    lightColor: "#f5f3ff",
    titleField: "description",
    referenceField: "expenseId",
    statusField: "status",
    dateField: "date",
    amountField: "amount",
    spreadsheetSheets: ["06_CARTOES"],
    tableColumns: ["expenseId", "date", "holder", "merchant", "amount", "status", "documentUrl"],
    fields: [
      { key: "expenseId", label: "Código da despesa", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID despesa"] },
      { key: "date", label: "Data", type: "date", required: true, aliases: ["Data"] },
      { key: "holder", label: "Titular", type: "text", required: true, aliases: ["Titular"] },
      { key: "cardEnding", label: "Final do cartão", type: "text", aliases: ["Final cartão"] },
      { key: "merchant", label: "Estabelecimento", type: "text", aliases: ["Estabelecimento"] },
      { key: "description", label: "Descrição", type: "text", required: true, aliases: ["Descrição"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "category", label: "Categoria", type: "text", aliases: ["Categoria"] },
      { key: "amount", label: "Valor", type: "currency", required: true, aliases: ["Valor"] },
      { key: "billingPeriod", label: "Mês da fatura", type: "date", help: "Mês em que esta compra aparecerá na fatura do cartão.", aliases: ["Competência fatura"] },
      { key: "documentUrl", label: "Nota fiscal ou recibo", type: "url", placeholder: "Cole o link do documento", aliases: ["Link documento"] },
      { key: "approval", label: "Situação da aprovação", type: "select", options: ["Pendente", "Aprovada", "Devolvida", "Rejeitada"], aliases: ["Aprovação"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Pendente", "Documento pendente", "Em análise", "Conferida", "Paga", "Reprovada"], aliases: ["Status"] },
      { key: "responsible", label: "Responsável", type: "text", aliases: ["Responsável"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "rentals",
    label: "Imóveis e aluguéis",
    shortLabel: "Aluguéis",
    eyebrow: "Operação",
    description:
      "Moradores, aluguel, proprietários e responsáveis por água, energia e internet.",
    color: "#c2410c",
    lightColor: "#fff7ed",
    titleField: "address",
    referenceField: "propertyId",
    statusField: "status",
    dateField: "endDate",
    amountField: "totalMonthly",
    spreadsheetSheets: ["08_IMOVEIS"],
    tableColumns: ["propertyId", "work", "address", "occupants", "totalMonthly", "status"],
    fields: [
      { key: "propertyId", label: "Código do imóvel", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID imóvel"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "address", label: "Endereço", type: "text", required: true, aliases: ["Endereço"] },
      { key: "city", label: "Cidade/UF", type: "text", aliases: ["Cidade/UF"] },
      { key: "landlord", label: "Para quem pagar o aluguel?", type: "text", required: true, placeholder: "Nome do proprietário ou imobiliária", aliases: ["Proprietário"] },
      { key: "contract", label: "Número do contrato", type: "text", aliases: ["Contrato"] },
      { key: "startDate", label: "Início do aluguel", type: "date", aliases: ["Início"] },
      { key: "endDate", label: "Fim do contrato", type: "date", aliases: ["Fim"] },
      { key: "monthlyRent", label: "Aluguel mensal", type: "currency", aliases: ["Aluguel mensal"] },
      { key: "capacity", label: "Capacidade máxima de moradores", type: "number", aliases: ["Capacidade"] },
      { key: "occupants", label: "Quantidade de moradores", type: "number", aliases: ["Ocupantes"] },
      { key: "residentNames", label: "Nomes dos moradores", type: "textarea", wide: true, placeholder: "Informe um nome por linha", aliases: ["Moradores", "Quem mora"] },
      { key: "waterPayee", label: "Para quem pagar a água?", type: "text", aliases: ["Responsável água"] },
      { key: "water", label: "Custo mensal de água", type: "currency", aliases: ["Água"] },
      { key: "energyPayee", label: "Para quem pagar a energia?", type: "text", aliases: ["Responsável energia", "Responsável luz"] },
      { key: "energy", label: "Custo mensal de energia", type: "currency", aliases: ["Energia"] },
      { key: "internetPayee", label: "Para quem pagar a internet?", type: "text", aliases: ["Responsável internet"] },
      { key: "internet", label: "Custo mensal de internet", type: "currency", aliases: ["Internet"] },
      { key: "totalMonthly", label: "Total mensal", type: "currency", aliases: ["Total mensal"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Ativo", "Em contratação", "A encerrar", "Encerrado"], aliases: ["Status"] },
      { key: "contractUrl", label: "Contrato digitalizado", type: "url", placeholder: "Cole o link do contrato", aliases: ["Link contrato"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "assets",
    label: "Máquinas",
    shortLabel: "Máquinas",
    eyebrow: "Operação",
    description:
      "Custos, locações, dias de inatividade e manutenções preventiva e corretiva.",
    color: "#b45309",
    lightColor: "#fffbeb",
    titleField: "description",
    referenceField: "assetId",
    statusField: "status",
    dateField: "nextMaintenance",
    amountField: "monthlyCost",
    spreadsheetSheets: ["09_ATIVOS_VEIC"],
    tableColumns: ["assetId", "description", "ownership", "work", "idleDays", "monthlyCost", "paymentStatus", "status"],
    fields: [
      { key: "assetId", label: "Código do equipamento ou veículo", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID ativo"] },
      { key: "type", label: "O que está sendo cadastrado?", type: "select", required: true, options: ["Máquina", "Equipamento", "Veículo", "Ferramenta"], aliases: ["Tipo"] },
      { key: "description", label: "Nome e modelo", type: "text", required: true, placeholder: "Ex.: Escavadeira Caterpillar 320", aliases: ["Descrição/modelo"] },
      { key: "serial", label: "Placa ou número de série", type: "text", aliases: ["Placa/série"] },
      { key: "ownership", label: "O equipamento é", type: "select", options: ["Próprio", "Locado", "Comodato"], help: "Comodato é quando outra empresa cede o equipamento para uso.", aliases: ["Posse"] },
      { key: "rentalCompany", label: "Locadora / fornecedor", type: "text", aliases: ["Locadora", "Fornecedor locação"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "responsible", label: "Responsável", type: "text", aliases: ["Responsável"] },
      { key: "currentActivity", label: "Atividade atual da máquina", type: "textarea", wide: true, placeholder: "Ex.: movimentação de solo na frente norte", help: "Informe o que a máquina está produzindo ou, se estiver parada, a condição operacional atual." },
      { key: "startDate", label: "Compra ou início da locação", type: "date", aliases: ["Aquisição/início contrato"] },
      { key: "rentalEndDate", label: "Fim da locação / contrato", type: "date", aliases: ["Fim da locação", "Fim contrato"] },
      { key: "rentalPeriodDays", label: "Quantidade de dias contratados", type: "number", help: "Exemplo: informe 30 quando a máquina foi locada por trinta dias.", aliases: ["Dias contratados", "Período locação"] },
      { key: "monthlyCost", label: "Valor total da locação / custo do período", type: "currency", help: "Exemplo: R$ 60.000,00 para uma locação de 30 dias. Esse valor forma o custo real da máquina.", aliases: ["Custo mensal", "Valor locação"] },
      { key: "dueDate", label: "Vencimento da locação", type: "date", aliases: ["Vencimento"] },
      { key: "paymentStatus", label: "Situação do pagamento da locação", type: "select", options: ["Pendente", "Parcial", "Pago", "Não se aplica"], aliases: ["Situação pagamento"] },
      { key: "paidAmount", label: "Valor já pago da locação", type: "currency", aliases: ["Valor pago"] },
      { key: "paymentDate", label: "Data do pagamento", type: "date", aliases: ["Data pagamento"] },
      { key: "nextMaintenance", label: "Próxima manutenção", type: "date", aliases: ["Próxima manutenção"] },
      { key: "meter", label: "Quilometragem ou horas de uso", type: "number", help: "Para veículos, informe os quilômetros. Para máquinas, informe o horímetro.", aliases: ["KM/horímetro"] },
      { key: "idleSince", label: "Inativo desde", type: "date", aliases: ["Inativo desde"] },
      { key: "idleDays", label: "Quantos dias ficou parado?", type: "number", aliases: ["Dias de ócio", "Dias inativo"] },
      { key: "preventiveCost", label: "Manutenção preventiva acumulada na ficha", type: "currency", help: "Campo histórico. Para novos serviços, use “Registrar manutenção ou ociosidade”.", aliases: ["Custo manutenção preventiva"] },
      { key: "correctiveCost", label: "Manutenção corretiva acumulada na ficha", type: "currency", help: "Campo histórico. Para novos serviços, use “Registrar manutenção ou ociosidade”.", aliases: ["Custo manutenção corretiva"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Ativo", "Em uso", "Ocioso", "Em manutenção", "Devolvido", "Baixado"], aliases: ["Status"] },
      { key: "documentsUrl", label: "Documentos do equipamento", type: "url", placeholder: "Cole o link de notas, contratos ou manutenções", aliases: ["Link documentos"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "asset_events",
    label: "Manutenção e Ociosidade",
    shortLabel: "Ocorrências de máquinas",
    eyebrow: "Operação de máquinas",
    description:
      "Histórico financeiro e operacional de manutenções, paralisações e perdas por equipamento.",
    color: "#ea580c",
    lightColor: "#fff7ed",
    titleField: "occurrenceTitle",
    referenceField: "occurrenceId",
    statusField: "status",
    dateField: "startDate",
    amountField: "maintenanceCost",
    spreadsheetSheets: [],
    tableColumns: ["occurrenceId", "assetName", "eventType", "cause", "idleDays", "maintenanceCost", "estimatedDowntimeLoss", "paymentStatus", "status"],
    fields: [
      { key: "occurrenceId", label: "Código da ocorrência", type: "text", required: true, help: "Criado automaticamente pelo sistema." },
      { key: "assetName", label: "Máquina ou equipamento", type: "text", required: true, help: "Selecione uma máquina já cadastrada." },
      { key: "assetId", label: "Código da máquina", type: "text", required: true, help: "Preenchido automaticamente ao selecionar a máquina." },
      { key: "work", label: "Obra vinculada", type: "text", help: "Preenchida a partir da ficha da máquina." },
      { key: "occurrenceTitle", label: "Título da ocorrência", type: "text", required: true, placeholder: "Ex.: Correção do sistema hidráulico" },
      { key: "eventType", label: "Tipo de ocorrência", type: "select", required: true, options: ["Manutenção corretiva", "Manutenção preventiva", "Ociosidade"] },
      { key: "cause", label: "Motivo da parada", type: "select", required: true, options: ["Não se aplica", "Chuva", "Maquinário quebrado", "Operador ausente", "Falta de material", "Aguardando liberação", "Manutenção programada", "Manutenção corretiva", "Falta de energia", "Acesso ou logística", "Outro"] },
      { key: "startDate", label: "Início da ocorrência", type: "date", required: true },
      { key: "endDate", label: "Fim / previsão de liberação", type: "date" },
      { key: "idleDays", label: "Dias sem produzir", type: "number", help: "Pode incluir chuva, quebra, manutenção ou outra indisponibilidade." },
      { key: "rentalValue", label: "Valor da locação considerado", type: "currency", help: "Copiado da ficha da máquina para preservar o cálculo histórico." },
      { key: "rentalPeriodDays", label: "Dias contratados considerados", type: "number", help: "Copiado da ficha da máquina." },
      { key: "dailyRentalRate", label: "Custo diário da máquina", type: "currency", help: "Calculado automaticamente: valor da locação ÷ dias contratados." },
      { key: "estimatedDowntimeLoss", label: "Perda estimada pela paralisação", type: "currency", help: "Calculada automaticamente: custo diário × dias sem produzir. Não é somada novamente ao custo contábil." },
      { key: "whatHappened", label: "O que aconteceu?", type: "textarea", wide: true, placeholder: "Descreva a condição que deixou a máquina improdutiva." },
      { key: "correctionDescription", label: "O que foi corrigido ou está sendo corrigido?", type: "textarea", wide: true, placeholder: "Informe o reparo, peça, serviço ou diagnóstico em andamento." },
      { key: "maintenanceSupplier", label: "Oficina / fornecedor da manutenção", type: "text" },
      { key: "maintenanceCost", label: "Custo total da manutenção", type: "currency", help: "Informe mão de obra, peças e demais custos do serviço." },
      { key: "paymentStatus", label: "Situação do pagamento da manutenção", type: "select", options: ["Pendente", "Parcial", "Pago", "Não se aplica"] },
      { key: "paidAmount", label: "Valor já pago da manutenção", type: "currency" },
      { key: "dueDate", label: "Vencimento da manutenção", type: "date" },
      { key: "paymentDate", label: "Data do pagamento da manutenção", type: "date" },
      { key: "status", label: "Andamento da ocorrência", type: "select", required: true, options: ["Aberta", "Em correção", "Concluída", "Encerrada"] },
      { key: "documentUrl", label: "Orçamento, nota ou ordem de serviço", type: "url", placeholder: "Cole o link do documento" },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "people",
    label: "Cadastro de Funcionários",
    shortLabel: "Cadastro de Funcionários",
    eyebrow: "RH",
    description:
      "Ficha profissional, vínculo, jornada, custos mensais, admissões e desligamentos.",
    color: "#be185d",
    lightColor: "#fdf2f8",
    titleField: "name",
    referenceField: "employeeCode",
    statusField: "status",
    dateField: "admissionDate",
    amountField: "salary",
    spreadsheetSheets: ["03_COLABORADORES"],
    tableColumns: ["employeeCode", "name", "role", "salary", "status", "terminationDate"],
    fields: [
      { key: "employeeCode", label: "Código do colaborador", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["Código colaborador"] },
      { key: "registration", label: "Matrícula na folha", type: "text", help: "Opcional. Informe somente se a contabilidade ou folha já utilizar matrícula.", aliases: ["Matrícula"] },
      { key: "name", label: "Nome completo", type: "text", required: true, aliases: ["Nome"] },
      { key: "photoUrl", label: "Foto do colaborador", type: "url", placeholder: "Cole o link protegido da foto", help: "Use um link autorizado do SharePoint ou OneDrive." },
      { key: "sex", label: "Sexo", type: "select", options: ["Não informado", "Feminino", "Masculino"] },
      { key: "birthDate", label: "Data de nascimento", type: "date", aliases: ["Nascimento"] },
      { key: "birthCity", label: "Cidade/UF de nascimento", type: "text" },
      { key: "birthCountry", label: "País de nascimento", type: "text", placeholder: "Ex.: Brasil" },
      { key: "nationality", label: "Nacionalidade", type: "text", placeholder: "Ex.: Brasileira" },
      { key: "maritalStatus", label: "Estado civil", type: "select", options: ["Não informado", "Solteiro(a)", "Casado(a)", "União estável", "Divorciado(a)", "Viúvo(a)"] },
      { key: "propertyRegime", label: "Regime de bens", type: "select", options: ["Não se aplica", "Comunhão parcial", "Comunhão universal", "Separação total", "Participação final nos aquestos"] },
      { key: "fatherName", label: "Filiação — pai", type: "text" },
      { key: "motherName", label: "Filiação — mãe", type: "text" },
      { key: "education", label: "Grau de instrução", type: "select", options: ["Não informado", "Fundamental incompleto", "Fundamental completo", "Médio incompleto", "Médio completo", "Superior incompleto", "Superior completo", "Pós-graduação", "Mestrado", "Doutorado"] },
      { key: "raceColor", label: "Raça/cor (eSocial)", type: "select", options: ["Não informado", "Branca", "Preta", "Parda", "Amarela", "Indígena"] },
      { key: "disabilityStatus", label: "Pessoa com deficiência", type: "select", options: ["Não", "Sim", "Em avaliação"] },
      { key: "disabilityType", label: "Tipo de deficiência", type: "select", options: ["Não se aplica", "Física", "Auditiva", "Visual", "Intelectual", "Mental", "Múltipla", "Reabilitado"] },
      { key: "disabilityQuota", label: "Cumpre cota de PCD/reabilitado?", type: "select", options: ["Não se aplica", "Sim", "Não"] },
      { key: "disabilityNotes", label: "Observações de acessibilidade", type: "textarea", wide: true },
      { key: "cpf", label: "CPF", type: "text", aliases: ["CPF"] },
      { key: "cpfVerificationStatus", label: "Situação cadastral do CPF", type: "select", options: ["Não consultado", "Regular", "Pendente de regularização", "Suspensa", "Cancelada", "Titular falecido", "Nula"], help: "Registre somente o resultado exibido na consulta oficial da Receita Federal. A consulta não informa situação econômica, financeira ou fiscal." },
      { key: "cpfVerificationDate", label: "Data da consulta do CPF", type: "date" },
      { key: "cpfProofUrl", label: "Comprovante cadastral do CPF", type: "url", placeholder: "Cole o link protegido do comprovante", help: "Guarde o comprovante em pasta restrita do SharePoint ou OneDrive; não use um link público." },
      { key: "pis", label: "PIS/NIS", type: "text", aliases: ["PIS", "NIS"] },
      { key: "pisRegistrationDate", label: "Data de inscrição no PIS", type: "date" },
      { key: "rgNumber", label: "RG — número", type: "text" },
      { key: "rgIssuer", label: "RG — órgão emissor", type: "text", placeholder: "Ex.: SSP" },
      { key: "rgState", label: "RG — UF", type: "text", placeholder: "Ex.: BA" },
      { key: "rgIssueDate", label: "RG — data de emissão", type: "date" },
      { key: "voterNumber", label: "Título eleitoral — número", type: "text" },
      { key: "voterZone", label: "Título — zona", type: "text" },
      { key: "voterSection", label: "Título — seção", type: "text" },
      { key: "voterState", label: "Título — UF", type: "text" },
      { key: "ctpsNumber", label: "CTPS — número", type: "text" },
      { key: "ctpsSeries", label: "CTPS — série", type: "text" },
      { key: "ctpsState", label: "CTPS — UF", type: "text" },
      { key: "ctpsIssueDate", label: "CTPS — data de emissão", type: "date" },
      { key: "cnhNumber", label: "CNH — número", type: "text" },
      { key: "cnhCategory", label: "CNH — categoria", type: "text", placeholder: "Ex.: AB" },
      { key: "cnhState", label: "CNH — UF", type: "text" },
      { key: "cnhValidity", label: "CNH — validade", type: "date" },
      { key: "cns", label: "Cartão Nacional de Saúde (CNS)", type: "text" },
      { key: "passportNumber", label: "Passaporte — número", type: "text" },
      { key: "passportCountry", label: "Passaporte — país emissor", type: "text" },
      { key: "passportValidity", label: "Passaporte — validade", type: "date" },
      { key: "visaType", label: "Visto — tipo", type: "text" },
      { key: "visaValidity", label: "Visto — validade", type: "date" },
      { key: "phone", label: "Telefone", type: "text", aliases: ["Telefone"] },
      { key: "personalEmail", label: "E-mail pessoal", type: "email", aliases: ["E-mail pessoal"] },
      { key: "corporateEmail", label: "E-mail corporativo", type: "email", aliases: ["E-mail corporativo"] },
      { key: "emergencyContact", label: "Contato de emergência", type: "text", aliases: ["Contato emergência"] },
      { key: "address", label: "Endereço residencial", type: "text" },
      { key: "addressNumber", label: "Número", type: "text" },
      { key: "addressComplement", label: "Complemento", type: "text" },
      { key: "district", label: "Bairro", type: "text" },
      { key: "city", label: "Cidade", type: "text" },
      { key: "state", label: "UF", type: "text" },
      { key: "postalCode", label: "CEP", type: "text" },
      { key: "dependents", label: "Dependentes para IRRF", type: "number", aliases: ["Dependentes"] },
      { key: "dependentDetails", label: "Ficha dos dependentes", type: "textarea", wide: true, placeholder: "Um dependente por bloco: nome, parentesco, CPF, nascimento, sexo, condição de IRRF e plano de saúde.", help: "Registre somente dependentes comprovados. A contabilidade deve validar o enquadramento no IRRF." },
      { key: "role", label: "Cargo", type: "text", aliases: ["Cargo"] },
      { key: "cbo", label: "CBO", type: "text", help: "Código Brasileiro de Ocupações aplicável ao cargo.", aliases: ["CBO"] },
      { key: "roleStartDate", label: "Início no cargo", type: "date" },
      { key: "department", label: "Setor", type: "text", aliases: ["Setor"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "workplace", label: "Local de trabalho", type: "text" },
      { key: "manager", label: "Gestor responsável", type: "text", aliases: ["Gestor"] },
      { key: "leader", label: "Líder imediato", type: "text" },
      { key: "union", label: "Sindicato / categoria", type: "text", aliases: ["Sindicato"] },
      { key: "collectiveAgreement", label: "Convenção coletiva", type: "text", aliases: ["Convenção coletiva"] },
      { key: "contractType", label: "Tipo de contrato", type: "select", options: ["Prazo indeterminado", "Prazo determinado", "Experiência", "Aprendiz", "Intermitente", "Outro"], aliases: ["Tipo contrato"] },
      { key: "admissionType", label: "Tipo de admissão", type: "select", options: ["Admissão", "Reemprego", "Transferência", "Sucessão", "Outro"] },
      { key: "admissionDate", label: "Data de admissão", type: "date", aliases: ["Admissão"] },
      { key: "esocialRegistration", label: "Matrícula eSocial", type: "text" },
      { key: "employmentGroup", label: "Categoria/vínculo eSocial", type: "text", placeholder: "Ex.: 101 — Empregado geral" },
      { key: "salaryType", label: "Tipo de salário", type: "select", options: ["Mensal", "Quinzenal", "Semanal", "Diário", "Horista", "Tarefa"] },
      { key: "monthlyHours", label: "Horas mensais contratadas", type: "number", help: "Usado como referência para cálculos. Não substitui o controle oficial de ponto.", aliases: ["Horas mensais"] },
      { key: "salary", label: "Salário mensal", type: "currency", aliases: ["Salário", "Salário-base", "Salário mensal"] },
      { key: "bankData", label: "Dados bancários para pagamento", type: "textarea", wide: true, aliases: ["Dados bancários"] },
      { key: "occupationalExamValidity", label: "Validade do exame ocupacional", type: "date", aliases: ["Validade ASO"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Ativo", "Afastado", "Férias", "Em desligamento", "Desligado"], aliases: ["Status"] },
      { key: "scheduleStartDate", label: "Início da jornada", type: "date" },
      { key: "weeklyHours", label: "Carga horária semanal", type: "number" },
      { key: "restDay", label: "Dia de repouso", type: "select", options: ["Domingo", "Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado", "Variável"] },
      { key: "workRegime", label: "Regime de trabalho", type: "select", options: ["Submetido a horário", "Atividade externa", "Cargo de gestão", "Teletrabalho"] },
      { key: "journeyType", label: "Tipo de jornada", type: "select", options: ["Normal", "12x36", "Dia fixo com folga variável", "Escala variável", "Outro"] },
      { key: "weeklySchedule", label: "Horários por dia da semana", type: "textarea", wide: true, placeholder: "Ex.: Segunda a sexta: 07:30–12:00 / 13:00–17:18; sábado: folga; domingo: DSR.", help: "Jornada contratual. O registro de ponto será integrado futuramente em módulo separado." },
      { key: "flexibleHours", label: "Horário flexível", type: "select", options: ["Não", "Sim", "Parcial"] },
      { key: "partTimeContract", label: "Contrato em regime parcial", type: "select", options: ["Não", "Sim"] },
      { key: "timeClockEmployeeId", label: "Identificador no sistema de ponto", type: "text", help: "Código que relacionará este colaborador ao cadastro do futuro sistema de ponto." },
      { key: "timeClockSyncStatus", label: "Situação da integração com o ponto", type: "select", options: ["Aguardando implantação", "Pronto para sincronizar", "Sincronizado", "Com divergência"] },
      { key: "lastTimeClockSync", label: "Última sincronização do ponto", type: "text", placeholder: "Preenchido automaticamente pela integração" },
      { key: "terminationDate", label: "Data do desligamento", type: "date", aliases: ["Data desligamento"] },
      { key: "terminationReason", label: "Motivo do desligamento", type: "text", aliases: ["Motivo desligamento"] },
      { key: "terminationType", label: "Tipo de rescisão", type: "text" },
      { key: "noticeType", label: "Tipo de aviso prévio", type: "select", options: ["Não se aplica", "Trabalhado", "Indenizado pelo empregador", "Indenizado pelo empregado", "Dispensado"] },
      { key: "noticeNotificationDate", label: "Data da notificação do aviso", type: "date" },
      { key: "noticeStartDate", label: "Início do aviso", type: "date" },
      { key: "noticeDays", label: "Dias de aviso", type: "number" },
      { key: "expectedContractEnd", label: "Término previsto do contrato", type: "date" },
      { key: "judicialProcess", label: "Processo judicial relacionado", type: "text" },
      { key: "esocialTerminationNotes", label: "Observações do desligamento para eSocial", type: "textarea", wide: true },
      { key: "accessProfile", label: "Acesso necessário no sistema", type: "text", placeholder: "Ex.: somente leitura, gestor ou financeiro", aliases: ["Perfil de acesso"] },
      { key: "documentsUrl", label: "Pasta restrita do colaborador", type: "url", placeholder: "Cole o link autorizado do SharePoint", aliases: ["Link documentos restritos"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "payroll",
    label: "Cálculo de Folha",
    shortLabel: "Cálculo de Folha",
    eyebrow: "RH • Motor de cálculo",
    description:
      "Simulações mensais com memória de cálculo, tributos, encargos e custo empresarial.",
    color: "#6d28d9",
    lightColor: "#f5f3ff",
    titleField: "employeeName",
    referenceField: "previewCode",
    statusField: "status",
    dateField: "competence",
    amountField: "netAmount",
    spreadsheetSheets: [],
    tableColumns: ["previewCode", "competence", "employeeName", "grossAmount", "inss", "irrf", "netAmount", "status"],
    fields: [
      { key: "previewCode", label: "Código do cálculo", type: "text", required: true },
      { key: "competence", label: "Competência", type: "date", required: true },
      { key: "employeeName", label: "Funcionário", type: "text", required: true },
      { key: "employeeCode", label: "Código do funcionário", type: "text" },
      { key: "role", label: "Cargo / função", type: "text" },
      { key: "workName", label: "Obra / centro de custo", type: "text" },
      { key: "additionalType", label: "Adicional ocupacional", type: "text" },
      { key: "additionalAmount", label: "Valor do adicional", type: "currency" },
      { key: "grossAmount", label: "Salário bruto", type: "currency" },
      { key: "inss", label: "INSS", type: "currency" },
      { key: "irrf", label: "IRRF", type: "currency" },
      { key: "netAmount", label: "Líquido estimado", type: "currency" },
      { key: "employerCost", label: "Custo empresarial", type: "currency" },
      { key: "employerCharges", label: "Encargos patronais", type: "currency" },
      { key: "rulesVersion", label: "Versão das regras", type: "text" },
      { key: "status", label: "Status", type: "select", options: ["Prévia", "Em conferência", "Validada pela contabilidade", "Cancelada"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "terminations",
    label: "Rescisão",
    shortLabel: "Rescisão",
    eyebrow: "RH • Desligamentos",
    description:
      "Cálculo integrado de verbas rescisórias, aviso prévio, férias, 13º, FGTS, tributos e descontos.",
    color: "#c2410c",
    lightColor: "#fff7ed",
    titleField: "employeeName",
    referenceField: "terminationCode",
    statusField: "status",
    dateField: "terminationDate",
    amountField: "netAmount",
    spreadsheetSheets: [],
    tableColumns: [
      "terminationCode",
      "employeeName",
      "terminationDate",
      "terminationTypeLabel",
      "grossAmount",
      "totalDeductions",
      "netAmount",
      "status",
    ],
    fields: [
      { key: "terminationCode", label: "Código do cálculo rescisório", type: "text", required: true },
      { key: "employeeName", label: "Funcionário", type: "text", required: true },
      { key: "employeeCode", label: "Código do funcionário", type: "text" },
      { key: "role", label: "Cargo / função", type: "text" },
      { key: "admissionDate", label: "Data de admissão", type: "date", required: true },
      { key: "terminationDate", label: "Data do desligamento", type: "date", required: true },
      { key: "deathDate", label: "Data do óbito", type: "date" },
      { key: "deathKnowledgeDate", label: "Data em que a empresa soube do óbito", type: "date" },
      { key: "deathRelatedToWork", label: "Óbito relacionado ao trabalho", type: "text" },
      { key: "catNumber", label: "Número / referência da CAT", type: "text" },
      { key: "deathPaymentRecipient", label: "Destinatário do pagamento no falecimento", type: "text" },
      { key: "contractType", label: "Tipo de contrato", type: "text" },
      { key: "expectedContractEnd", label: "Término previsto do contrato", type: "date" },
      { key: "reciprocalEarlyTerminationClause", label: "Cláusula assecuratória de rescisão antecipada", type: "text" },
      { key: "projectedTerminationDate", label: "Término projetado pelo aviso", type: "date" },
      { key: "terminationTypeLabel", label: "Motivo do desligamento", type: "text", required: true },
      { key: "esocialReasonCode", label: "Código do motivo no eSocial", type: "text" },
      { key: "noticeTypeLabel", label: "Modalidade do aviso prévio", type: "text" },
      { key: "noticeDays", label: "Dias de aviso prévio", type: "number" },
      { key: "noticeProjectionDays", label: "Dias projetados do aviso indenizado", type: "number" },
      { key: "baseSalary", label: "Salário-base", type: "currency" },
      { key: "variableAverage", label: "Média de verbas variáveis", type: "currency" },
      { key: "remunerationBase", label: "Remuneração-base da rescisão", type: "currency" },
      { key: "salaryBalance", label: "Saldo de salário", type: "currency" },
      { key: "noticeAmount", label: "Aviso prévio indenizado", type: "currency" },
      { key: "thirteenthBaseMonths", label: "Avos de 13º do período trabalhado", type: "number" },
      { key: "thirteenthNoticeMonths", label: "Avos de 13º projetados pelo aviso", type: "number" },
      { key: "thirteenthBaseSalary", label: "13º proporcional sem projeção", type: "currency" },
      { key: "thirteenthNoticeSalary", label: "13º sobre aviso indenizado", type: "currency" },
      { key: "thirteenthSalary", label: "13º salário proporcional", type: "currency" },
      { key: "accruedVacation", label: "Férias vencidas", type: "currency" },
      { key: "proportionalVacation", label: "Férias proporcionais", type: "currency" },
      { key: "vacationThird", label: "Terço constitucional", type: "currency" },
      { key: "fixedTermIndemnity", label: "Indenização de contrato a prazo", type: "currency" },
      { key: "grossAmount", label: "Total bruto", type: "currency" },
      { key: "inss", label: "INSS total", type: "currency" },
      { key: "irrf", label: "IRRF total", type: "currency" },
      { key: "noticeDeduction", label: "Desconto de aviso não cumprido", type: "currency" },
      { key: "totalDeductions", label: "Total de descontos", type: "currency" },
      { key: "netAmount", label: "Líquido rescisório estimado", type: "currency" },
      { key: "fgtsMonthlyBase", label: "Base mensal do FGTS", type: "currency" },
      { key: "fgtsThirteenthBase", label: "Base de 13º do FGTS", type: "currency" },
      { key: "fgtsNoticeBase", label: "Base do aviso indenizado no FGTS", type: "currency" },
      { key: "fgtsMonthlyDeposit", label: "FGTS sobre verbas mensais", type: "currency" },
      { key: "fgtsThirteenthDeposit", label: "FGTS sobre 13º", type: "currency" },
      { key: "fgtsNoticeDeposit", label: "FGTS sobre aviso indenizado", type: "currency" },
      { key: "fgtsSeveranceDeposit", label: "FGTS rescisório estimado", type: "currency" },
      { key: "fgtsFine", label: "Indenização compensatória do FGTS", type: "currency" },
      { key: "employerSocialCharges", label: "Encargos patronais estimados", type: "currency" },
      { key: "employerCost", label: "Custo total estimado da empresa", type: "currency" },
      { key: "payrollHistoryCount", label: "Cálculos de folha reaproveitados", type: "number" },
      { key: "rulesVersion", label: "Versão das regras", type: "text" },
      { key: "mosVersion", label: "Versão do MOS utilizada", type: "text" },
      { key: "layoutVersion", label: "Versão do leiaute eSocial", type: "text" },
      { key: "esocialDeadlineBaseDate", label: "Prazo-base operacional do S-2299", type: "date" },
      { key: "paymentDeadlineBaseDate", label: "Prazo-base operacional de pagamento", type: "date" },
      { key: "esocialIndApurIR", label: "Indicador de apuração do IR no eSocial", type: "text" },
      { key: "esocialPaymentEvent", label: "Destino declaratório futuro do pagamento", type: "text" },
      { key: "esocialStatus", label: "Situação do S-2299", type: "select", options: ["Não transmitido — prévia", "Não preparado", "Em preparação", "Validado internamente"] },
      { key: "fgtsCheckStatus", label: "Conferência no FGTS Digital", type: "select", options: ["Pendente", "Conferido", "Com divergência"] },
      { key: "status", label: "Status", type: "select", options: ["Prévia — não transmitida", "Em conferência", "Aguardando documentos", "Validada pelo RH", "Validada pela contabilidade", "Cancelada"] },
      { key: "notes", label: "Observações e justificativas", type: "textarea", wide: true },
    ],
  },
  {
    id: "compliance",
    label: "eSocial, Reinf e Compliance",
    shortLabel: "Fiscal e Compliance",
    eyebrow: "Fiscal • Obrigações digitais",
    description:
      "Preparação, validação, protocolo, recibo e retorno dos eventos legais da empresa e das obras.",
    color: "#0f766e",
    lightColor: "#ecfdf5",
    titleField: "eventName",
    referenceField: "eventId",
    statusField: "status",
    dateField: "competence",
    amountField: "",
    spreadsheetSheets: [],
    tableColumns: ["eventId", "system", "eventCode", "competence", "environment", "layoutVersion", "status"],
    fields: [
      { key: "eventId", label: "Identificador interno do evento", type: "text", required: true },
      { key: "eventName", label: "Nome do evento / obrigação", type: "text", required: true },
      { key: "system", label: "Sistema oficial", type: "select", required: true, options: ["eSocial", "EFD-Reinf", "CNO", "DCTFWeb", "SERO", "Outro"] },
      { key: "eventCode", label: "Código do evento", type: "text", placeholder: "Ex.: S-1200, S-1299 ou R-2010" },
      { key: "eventGroup", label: "Grupo do evento", type: "select", options: ["Tabelas", "Não periódico", "Periódico", "Retenções", "Fechamento", "Cadastro de obra", "Regularização"] },
      { key: "competence", label: "Competência / referência", type: "date", required: true },
      { key: "environment", label: "Ambiente", type: "select", options: ["Produção restrita", "Produção", "Cadastro interno"] },
      { key: "layoutVersion", label: "Versão do leiaute", type: "text", placeholder: "Ex.: S-1.3 ou 2.1.2b" },
      { key: "companyCnpj", label: "CNPJ do declarante", type: "text" },
      { key: "work", label: "Obra / centro de custo", type: "text" },
      { key: "cno", label: "CNO relacionado", type: "text" },
      { key: "ruleSet", label: "Conjunto de regras aplicado", type: "text", placeholder: "Ex.: BR-FOLHA-2026.2" },
      { key: "validationStatus", label: "Validação interna", type: "select", options: ["Não iniciada", "Com pendências", "Validado internamente", "Rejeitado internamente"] },
      { key: "certificateType", label: "Certificado para assinatura", type: "select", options: ["Não configurado", "A1", "A3", "Procuração eletrônica"] },
      { key: "batchProtocol", label: "Protocolo do lote", type: "text" },
      { key: "receiptNumber", label: "Recibo do evento", type: "text" },
      { key: "payloadHash", label: "Hash do XML / conteúdo", type: "text" },
      { key: "status", label: "Status", type: "select", required: true, options: ["Rascunho", "Validado internamente", "Aguardando certificado", "Pronto para transmissão", "Transmitido", "Em processamento", "Processado com sucesso", "Rejeitado"] },
      { key: "xmlUrl", label: "XML assinado", type: "url", help: "Guarde o arquivo em repositório restrito. O site registra somente o link autorizado." },
      { key: "returnUrl", label: "Retorno / recibo oficial", type: "url" },
      { key: "responsible", label: "Responsável", type: "text" },
      { key: "notes", label: "Pendências e observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "rules",
    label: "Motor de Regras",
    shortLabel: "Motor de Regras",
    eyebrow: "Compliance • Versionamento",
    description:
      "Regras de folha, incidências, convenções coletivas e validações por vigência e escopo.",
    color: "#4f46e5",
    lightColor: "#eef2ff",
    titleField: "name",
    referenceField: "ruleCode",
    statusField: "status",
    dateField: "validFrom",
    amountField: "",
    spreadsheetSheets: [],
    tableColumns: ["ruleCode", "name", "domain", "scope", "region", "validFrom", "version", "status"],
    fields: [
      { key: "ruleCode", label: "Código da regra", type: "text", required: true },
      { key: "name", label: "Nome da regra", type: "text", required: true },
      { key: "domain", label: "Domínio", type: "select", required: true, options: ["Folha", "eSocial", "EFD-Reinf", "CNO", "Retenções", "Convenção coletiva", "Financeiro"] },
      { key: "sourceBody", label: "Fonte normativa / órgão", type: "text", placeholder: "Ex.: eSocial, Receita Federal, MTE ou convenção coletiva" },
      { key: "sourceUrl", label: "Fonte oficial", type: "url" },
      { key: "scope", label: "Escopo", type: "select", options: ["Nacional", "Empresa", "Obra", "Sindicato", "Cargo", "Rubrica"] },
      { key: "region", label: "UF / região", type: "text", placeholder: "Ex.: BA ou Nacional" },
      { key: "union", label: "Sindicato / convenção", type: "text" },
      { key: "cnae", label: "CNAE aplicável", type: "text" },
      { key: "layoutVersion", label: "Versão de leiaute", type: "text" },
      { key: "version", label: "Versão interna", type: "text", required: true },
      { key: "priority", label: "Prioridade", type: "number", help: "Regras mais específicas devem possuir prioridade maior." },
      { key: "validFrom", label: "Início da vigência", type: "date", required: true },
      { key: "validUntil", label: "Fim da vigência", type: "date" },
      { key: "incidence", label: "Incidências e bases afetadas", type: "textarea", wide: true, placeholder: "Descreva INSS, IRRF, FGTS, eSocial e demais reflexos." },
      { key: "expression", label: "Expressão / procedimento de cálculo", type: "textarea", wide: true, help: "Descrição auditável da regra; não executa código arbitrário." },
      { key: "approvalEvidence", label: "Evidência de homologação", type: "url" },
      { key: "status", label: "Status", type: "select", required: true, options: ["Rascunho", "Em homologação", "Ativa", "Suspensa", "Revogada"] },
      { key: "responsible", label: "Responsável pela homologação", type: "text" },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "food",
    label: "Alimentação",
    shortLabel: "Alimentação",
    eyebrow: "Operação",
    description:
      "Custo por pessoa, quantidades previstas, entregues e retiradas em cada obra.",
    color: "#15803d",
    lightColor: "#f0fdf4",
    titleField: "meal",
    referenceField: "entryId",
    statusField: "status",
    dateField: "date",
    amountField: "billedTotal",
    spreadsheetSheets: ["10_ALIMENTACAO"],
    tableColumns: ["entryId", "date", "work", "meal", "expectedQty", "takenQty", "unitPrice", "billedTotal", "status"],
    fields: [
      { key: "entryId", label: "Código do registro de alimentação", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID lançamento"] },
      { key: "date", label: "Data", type: "date", required: true, aliases: ["Data"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "supplierCode", label: "Código interno do fornecedor", type: "text", help: "Opcional.", aliases: ["Código fornecedor"] },
      { key: "supplier", label: "Fornecedor", type: "text", aliases: ["Fornecedor"] },
      { key: "meal", label: "Refeição", type: "select", required: true, options: ["Café da manhã", "Almoço", "Jantar", "Lanche"], aliases: ["Refeição"] },
      { key: "expectedQty", label: "Quantas pessoas estavam previstas?", type: "number", aliases: ["Qtd. prevista"] },
      { key: "deliveredQty", label: "Quantas refeições foram entregues?", type: "number", aliases: ["Qtd. entregue"] },
      { key: "takenQty", label: "Quantas refeições foram retiradas?", type: "number", aliases: ["Qtd. retirada"] },
      { key: "whoTook", label: "Quem retirou as refeições?", type: "textarea", wide: true, placeholder: "Informe os nomes ou cole a relação", aliases: ["Quem retirou", "Quem pegou"] },
      { key: "notTaken", label: "Quem não retirou ou qual foi o problema?", type: "textarea", wide: true, placeholder: "Ex.: João não retirou; 2 refeições faltaram", aliases: ["Quem não retirou", "Quem não pegou"] },
      { key: "unitPrice", label: "Custo por pessoa", type: "currency", aliases: ["Preço unitário"] },
      { key: "expectedTotal", label: "Valor total esperado", type: "currency", aliases: ["Total esperado"] },
      { key: "billedTotal", label: "Valor cobrado pelo fornecedor", type: "currency", aliases: ["Total faturado"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Previsto", "Entregue", "Em conferência", "Conferido", "Divergência"], aliases: ["Status"] },
      { key: "invoiceUrl", label: "Nota fiscal da alimentação", type: "url", placeholder: "Cole o link da nota", aliases: ["Link nota"] },
      { key: "responsible", label: "Responsável", type: "text", aliases: ["Responsável"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "taxes",
    label: "Impostos e obrigações",
    shortLabel: "Impostos",
    eyebrow: "Fiscal",
    description:
      "Competência, vencimento, guia, pagamento e comprovantes das obrigações fiscais.",
    color: "#dc2626",
    lightColor: "#fef2f2",
    titleField: "tax",
    referenceField: "taxId",
    statusField: "status",
    dateField: "dueDate",
    amountField: "expectedAmount",
    spreadsheetSheets: ["11_IMPOSTOS"],
    tableColumns: ["taxId", "tax", "period", "dueDate", "expectedAmount", "status", "guideUrl"],
    fields: [
      { key: "taxId", label: "Código do imposto", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID obrigação"] },
      { key: "tax", label: "Nome do imposto ou obrigação", type: "text", required: true, placeholder: "Ex.: FGTS, INSS, DAS ou ISS", aliases: ["Tributo/obrigação"] },
      { key: "entity", label: "Empresa responsável (CNPJ)", type: "text", aliases: ["Entidade/CNPJ"] },
      { key: "period", label: "Mês de referência", type: "date", help: "Período ao qual o imposto se refere.", aliases: ["Competência"] },
      { key: "dueDate", label: "Vencimento", type: "date", required: true, aliases: ["Vencimento"] },
      { key: "expectedAmount", label: "Valor a pagar", type: "currency", required: true, aliases: ["Valor previsto"] },
      { key: "guideReceived", label: "A guia de pagamento já foi recebida?", type: "select", options: ["Sim", "Não"], aliases: ["Guia recebida?"] },
      { key: "guideUrl", label: "Guia de pagamento", type: "url", placeholder: "Cole o link da guia", aliases: ["Link guia"] },
      { key: "status", label: "Status", type: "select", required: true, options: statusFinanceiro, aliases: ["Status"] },
      { key: "paymentDate", label: "Data do pagamento", type: "date", aliases: ["Data pagamento"] },
      { key: "paidAmount", label: "Valor pago", type: "currency", aliases: ["Valor pago"] },
      { key: "receiptUrl", label: "Comprovante de pagamento", type: "url", placeholder: "Cole o link do comprovante", aliases: ["Link comprovante"] },
      { key: "responsible", label: "Responsável", type: "text", aliases: ["Responsável"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "purchases",
    label: "Compras de materiais",
    shortLabel: "Compras",
    eyebrow: "Suprimentos",
    description:
      "Solicitações de materiais encaminhadas para análise e decisão por obra.",
    color: "#0369a1",
    lightColor: "#f0f9ff",
    titleField: "material",
    referenceField: "requestId",
    statusField: "status",
    dateField: "requestDate",
    amountField: "totalAmount",
    spreadsheetSheets: ["07_COMPRAS"],
    tableColumns: ["requestId", "requestDate", "work", "material", "quantity", "totalAmount", "status", "documentsUrl"],
    fields: [
      { key: "requestId", label: "Código da solicitação", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID solicitação"] },
      { key: "requestDate", label: "Data da solicitação", type: "date", required: true, aliases: ["Data"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "requester", label: "Solicitante", type: "text", aliases: ["Solicitante"] },
      { key: "material", label: "O que precisa ser comprado?", type: "text", required: true, placeholder: "Ex.: 50 sacos de cimento CP-II", aliases: ["Material/serviço"] },
      { key: "quantity", label: "Quantidade", type: "number", aliases: ["Quantidade"] },
      { key: "unit", label: "Unidade de medida", type: "text", placeholder: "Ex.: unidade, metro, kg ou saco", aliases: ["Unidade"] },
      { key: "neededDate", label: "Quando o material é necessário?", type: "date", aliases: ["Data necessária"] },
      { key: "priority", label: "Prioridade", type: "select", options: ["Baixa", "Média", "Alta", "Urgente"], aliases: ["Prioridade"] },
      { key: "minimumQuotes", label: "Quantos orçamentos são necessários?", type: "number", help: "Quantidade mínima de fornecedores que devem ser consultados.", aliases: ["Cotações mínimas"] },
      { key: "quotesReceived", label: "Quantos orçamentos foram recebidos?", type: "number", aliases: ["Cotações recebidas"] },
      { key: "supplier", label: "Fornecedor", type: "text", aliases: ["Fornecedor"] },
      { key: "totalAmount", label: "Valor total", type: "currency", aliases: ["Valor total"] },
      { key: "orderNumber", label: "Número do pedido", type: "text", aliases: ["Nº pedido"] },
      { key: "receivedDate", label: "Data do recebimento", type: "date", aliases: ["Data recebimento"] },
      { key: "receivedQty", label: "Quantidade recebida", type: "number", aliases: ["Qtd. recebida"] },
      { key: "status", label: "Status", type: "select", required: true, options: ["Aguardando análise", "Aprovado", "Reprovado"], aliases: ["Status"] },
      { key: "documentsUrl", label: "Orçamentos, pedido e nota fiscal", type: "url", placeholder: "Cole o link da pasta com os documentos", aliases: ["Link documentos"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "documents",
    label: "Documentos e links",
    shortLabel: "Documentos",
    eyebrow: "SharePoint",
    description:
      "Índice de documentos oficiais, validade, responsável, versão e link no SharePoint.",
    color: "#475569",
    lightColor: "#f8fafc",
    titleField: "type",
    referenceField: "documentId",
    statusField: "status",
    dateField: "validity",
    amountField: "",
    spreadsheetSheets: ["12_DOCUMENTOS"],
    tableColumns: ["documentId", "type", "moduleName", "relatedCode", "validity", "status", "sharepointUrl"],
    fields: [
      { key: "documentId", label: "Código do documento", type: "text", required: true, help: "Criado automaticamente pelo sistema.", aliases: ["ID documento"] },
      { key: "type", label: "Que documento é este?", type: "text", required: true, placeholder: "Ex.: contrato, nota fiscal ou laudo", aliases: ["Tipo"] },
      { key: "moduleName", label: "Área relacionada", type: "text", placeholder: "Ex.: Obras, Financeiro ou RH", aliases: ["Módulo"] },
      { key: "relatedCode", label: "Código do registro relacionado", type: "text", help: "Opcional. Use para ligar este documento a uma obra, compra ou pagamento.", aliases: ["Código relacionado"] },
      { key: "work", label: "Obra", type: "text", aliases: ["Obra"] },
      { key: "date", label: "Data do documento", type: "date", aliases: ["Competência/data"] },
      { key: "confidentiality", label: "Quem pode acessar?", type: "select", options: ["Geral", "Restrito à área", "Confidencial"], aliases: ["Confidencialidade"] },
      { key: "validity", label: "Validade", type: "date", aliases: ["Validade"] },
      { key: "status", label: "Status", type: "select", options: ["Vigente", "Vence em 30 dias", "Vencido", "Substituído", "Arquivado"], aliases: ["Status"] },
      { key: "responsible", label: "Responsável", type: "text", aliases: ["Responsável"] },
      { key: "sharepointUrl", label: "Onde o documento está salvo?", type: "url", required: true, placeholder: "Cole o link do SharePoint ou OneDrive", aliases: ["Link SharePoint"] },
      { key: "version", label: "Versão", type: "text", aliases: ["Versão"] },
      { key: "notes", label: "Observações", type: "textarea", wide: true, aliases: ["Observações"] },
    ],
  },
  {
    id: "emails",
    label: "E-mails corporativos",
    shortLabel: "E-mails",
    eyebrow: "Microsoft 365",
    description:
      "Inventário das contas @betaconstrutora.com.br, licenças, MFA e caixas compartilhadas.",
    color: "#0078d4",
    lightColor: "#eff6ff",
    titleField: "email",
    referenceField: "email",
    statusField: "status",
    dateField: "activationDate",
    amountField: "",
    spreadsheetSheets: [],
    tableColumns: ["email", "displayName", "department", "mailboxType", "license", "mfa", "status"],
    fields: [
      { key: "displayName", label: "Nome que aparecerá no Outlook", type: "text", required: true, placeholder: "Ex.: Financeiro Beta Construtora" },
      { key: "email", label: "E-mail @betaconstrutora.com.br", type: "email", required: true, placeholder: "nome@betaconstrutora.com.br" },
      { key: "department", label: "Setor", type: "text" },
      { key: "mailboxType", label: "Como este e-mail será usado?", type: "select", options: ["Usuário individual", "Caixa compartilhada", "Grupo", "Alias"], help: "Caixa compartilhada é usada por uma equipe. Alias é um endereço adicional que entrega na mesma caixa." },
      { key: "license", label: "Licença Microsoft 365", type: "select", options: ["Business Basic", "Business Standard", "Business Premium", "Sem licença"] },
      { key: "mfa", label: "Verificação em duas etapas (MFA)", type: "select", options: ["Ativo", "Pendente", "Não aplicável"], help: "Proteção que exige uma segunda confirmação além da senha." },
      { key: "encryption", label: "Proteção e criptografia do e-mail", type: "select", options: ["Política aplicada", "Pendente de configuração", "Não validado"] },
      { key: "activationDate", label: "Data de ativação", type: "date" },
      { key: "status", label: "Status", type: "select", required: true, options: ["Planejada", "Em configuração", "Ativa", "Bloqueada", "Desativada"] },
      { key: "adminOwner", label: "Quem administrará esta conta?", type: "text" },
      { key: "outlookUrl", label: "Link do Outlook", type: "url", placeholder: "https://outlook.office.com/mail/" },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
  {
    id: "m365",
    label: "Integrações Microsoft 365",
    shortLabel: "Integrações",
    eyebrow: "Administração",
    description:
      "Links oficiais e situação da publicação no Teams, SharePoint, Lists, Forms e Power Automate.",
    color: "#0f6cbd",
    lightColor: "#eff6ff",
    titleField: "name",
    referenceField: "service",
    statusField: "status",
    dateField: "publishedDate",
    amountField: "",
    spreadsheetSheets: [],
    tableColumns: ["service", "name", "owner", "status", "url"],
    fields: [
      { key: "service", label: "Aplicativo Microsoft", type: "select", required: true, options: ["Teams", "SharePoint", "Microsoft Lists", "Microsoft Forms", "Power Automate", "Outlook/Exchange", "Excel"] },
      { key: "name", label: "Nome da integração", type: "text", required: true, placeholder: "Ex.: Site de documentos da Beta" },
      { key: "owner", label: "Responsável", type: "text" },
      { key: "status", label: "Status", type: "select", required: true, options: ["Planejado", "Em configuração", "Em teste", "Publicado", "Bloqueado"] },
      { key: "publishedDate", label: "Data de publicação", type: "date" },
      { key: "url", label: "Link oficial", type: "url" },
      { key: "notes", label: "Observações", type: "textarea", wide: true },
    ],
  },
];

export const moduleMap = Object.fromEntries(
  moduleDefinitions.map((module) => [module.id, module]),
) as Record<string, ModuleDefinition>;

const internalCodeFieldKeys = new Set([
  "code",
  "measurementId",
  "workCode",
  "logId",
  "supplierCode",
  "accountId",
  "expenseId",
  "propertyId",
  "assetId",
  "occurrenceId",
  "employeeCode",
  "previewCode",
  "terminationCode",
  "eventId",
  "ruleCode",
  "entryId",
  "taxId",
  "requestId",
  "documentId",
  "relatedCode",
  "timeClockEmployeeId",
]);

const modulesWithInternalReferences = new Set([
  "works",
  "worklogs",
  "suppliers",
  "expenses",
  "cards",
  "rentals",
  "assets",
  "asset_events",
  "people",
  "payroll",
  "terminations",
  "compliance",
  "rules",
  "food",
  "taxes",
  "purchases",
  "documents",
  "contractors",
]);

export function isInternalCodeField(
  module: ModuleDefinition,
  fieldKey: string,
) {
  return (
    internalCodeFieldKeys.has(fieldKey) ||
    (modulesWithInternalReferences.has(module.id) &&
      fieldKey === module.referenceField)
  );
}

export function hasInternalRecordReference(moduleId: string) {
  return modulesWithInternalReferences.has(moduleId);
}

export function isHiddenOperationalModule(moduleId: string) {
  return moduleId === "contractors";
}

export const moduleTips: Record<string, string> = {
  works:
    "Cadastre cada obra uma única vez, informe a linha de base, o avanço comprovado e o que está sendo executado. Depois, selecione essa mesma obra nos diários, compras, pessoas e equipamentos.",
  worklogs:
    "Registre diariamente o que foi executado. Quando houver perda de produção, informe as horas e a causa para que o painel mostre o impacto real por obra.",
  suppliers:
    "Antes do primeiro pagamento, confira o CNPJ, os dados bancários e os documentos do fornecedor.",
  expenses:
    "Comece pelo fornecedor, pelo que será pago e pelo vencimento. Anexe a nota fiscal quando ela estiver disponível.",
  cards:
    "Registre cada compra do cartão separadamente e sempre vincule a nota ou o recibo.",
  rentals:
    "Informe quem mora no imóvel e para quem cada conta deve ser paga. Isso evita dúvidas no fechamento do mês.",
  assets:
    "Cadastre o contrato e o pagamento da máquina. Depois use “Registrar manutenção ou ociosidade” para documentar cada parada, reparo, custo e perda estimada.",
  asset_events:
    "Selecione a máquina, informe a causa e os dias parados. O sistema calcula o custo diário e a perda estimada sem duplicar o custo contábil.",
  people:
    "Este módulo acompanha quadro e custos de pessoal. Documentos pessoais devem ficar apenas em pastas restritas.",
  food:
    "Compare pessoas previstas, refeições entregues e retiradas para identificar desperdícios ou faltas.",
  taxes:
    "Registre o vencimento assim que receber a obrigação e anexe a guia e o comprovante para manter o histórico completo.",
  purchases:
    "Descreva claramente o material, a quantidade, a obra e a data necessária antes de iniciar as cotações.",
  documents:
    "O sistema guarda o índice e o link. O arquivo original deve permanecer no SharePoint ou OneDrive autorizado.",
  emails:
    "Planeje aqui cada conta corporativa. A criação real do e-mail será feita no Microsoft 365 Admin.",
  m365:
    "Registre os links publicados para que a equipe saiba onde encontrar cada recurso do Microsoft 365.",
  payroll:
    "Simule, confira a memória de cálculo e valide com a contabilidade antes de qualquer fechamento oficial.",
  terminations:
    "Selecione o funcionário para reaproveitar cadastro e histórico do Cálculo de Folha. Revise motivo, aviso, férias, médias, FGTS e descontos antes da validação contábil.",
  contractors:
    "Cadastre o terceiro, vincule a obra e atualize a execução comprovada do escopo. Confira equipe, produtividade, contrato, retenções, nota fiscal e aprovação antes do pagamento.",
  compliance:
    "Validação interna não significa transmissão oficial. Somente marque como transmitido quando houver protocolo e, como processado, quando houver recibo ou retorno.",
  rules:
    "Cadastre a fonte, a vigência e o escopo. Uma regra só deve ficar ativa depois de homologação contábil, trabalhista ou fiscal.",
};

export const navigationGroups = [
  { label: "GESTÃO", items: ["dashboard"] },
  { label: "FINANCEIRO & SUPRIMENTOS", items: ["expenses", "cards", "purchases", "suppliers"] },
  { label: "ENGENHARIA & MÁQUINAS", items: ["works", "worklogs", "assets"] },
  { label: "PESSOAS", items: ["people", "payroll", "terminations"] },
  { label: "FISCAL & COMPLIANCE", items: ["compliance", "rules", "taxes"] },
  { label: "OPERAÇÃO & DOCUMENTOS", items: ["rentals", "food", "documents"] },
  { label: "MICROSOFT 365", items: ["emails", "m365"] },
];

export function fieldByKey(module: ModuleDefinition, key: string) {
  return module.fields.find((field) => field.key === key);
}

export function normalizeHeader(value: unknown) {
  return String(value ?? "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export function amountForPayload(
  module: ModuleDefinition,
  payload: Record<string, unknown>,
) {
  if (module.id === "rentals") {
    const total =
      Number(payload.monthlyRent || 0) +
      Number(payload.water || 0) +
      Number(payload.energy || 0) +
      Number(payload.internet || 0);
    return Number(payload.totalMonthly || total || 0);
  }
  if (module.id === "people") {
    return Number(payload.salary || 0);
  }
  if (module.id === "food") {
    const total = Number(payload.takenQty || 0) * Number(payload.unitPrice || 0);
    return Number(payload.billedTotal || total || 0);
  }
  if (!module.amountField) return 0;
  return Number(payload[module.amountField] || 0);
}
