export const DEMO_SOURCE = "Demonstração — dados fictícios";

type DemoRecord = {
  module: string;
  title: string;
  reference: string;
  status: string;
  recordDate: string;
  amount: number;
  payload: Record<string, unknown>;
  source: string;
};

function demo(
  module: string,
  title: string,
  reference: string,
  status: string,
  recordDate: string,
  amount: number,
  payload: Record<string, unknown>,
): DemoRecord {
  return {
    module,
    title,
    reference,
    status,
    recordDate,
    amount,
    payload: {
      ...payload,
      notes: "REGISTRO FICTÍCIO PARA TESTE — não utilizar na operação real.",
    },
    source: DEMO_SOURCE,
  };
}

const docs = (name: string) => `https://example.com/beta-teste/${name}`;

export const demoRecords: DemoRecord[] = [
  demo("works", "Residencial Horizonte — Obra Teste", "TST-OBR-001", "Ativa", "2026-07-15", 1850000, {
    code: "TST-OBR-001", cno: "00.000.00000/00", name: "Residencial Horizonte — Obra Teste", client: "Cliente Demonstração Alfa",
    constructionType: "Edificação",
    city: "Campinas/SP", costCenter: "CC-TESTE-001", manager: "Gestor Teste 01",
    foreman: "Encarregado Teste 01", status: "Ativa", startDate: "2026-07-15",
    endDate: "2027-03-30", budget: 1850000, realizedCost: 620000,
    openCommitments: 310000, estimatedCostToComplete: 1290000,
    channel: "obra.teste01@betaconstrutora.com.br",
    plannedProgress: 23, physicalProgress: 18, ownTeamProgress: 21,
    requiredOwnTeamCount: 20,
    scheduleDelayDays: 5, dailyWorkHours: 8,
    currentStage: "Alvenaria", currentStageProgress: 42,
    currentProcess: "Elevação das paredes dos apartamentos 101 a 104 do bloco A e conferência dos vãos de portas e janelas.",
    currentScope: "Elevação da alvenaria do bloco A e passagem das primeiras tubulações elétricas embutidas.",
    totalPlannedDays: 258, nextMilestone: "Concluir a alvenaria do bloco A",
    nextMilestoneDate: "2026-08-07", riskLevel: "Atenção",
    scheduleNotes: "Reprogramar a concretagem e recuperar o desvio causado por chuva e indisponibilidade pontual da betoneira.",
    cnoStatus: "Em conferência", cnoResponsible: "Responsável Teste",
    cnoLastValidation: "2026-07-25", taxLotation: "LOT-TST-001",
    cprbMode: "A parametrizar", dailyLogUrl: docs("diario-obra-001"),
    documentsUrl: docs("obra-001"),
  }),
  demo("works", "Galpão Industrial Modelo — Obra Teste", "TST-OBR-002", "Planejada", "2026-08-10", 940000, {
    code: "TST-OBR-002", cno: "11.111.11111/11", name: "Galpão Industrial Modelo — Obra Teste", client: "Cliente Demonstração Beta",
    constructionType: "Obra de infraestrutura",
    city: "Hortolândia/SP", costCenter: "CC-TESTE-002", manager: "Gestor Teste 02",
    foreman: "Encarregado Teste 02", status: "Planejada", startDate: "2026-08-10",
    endDate: "2027-01-20", budget: 940000, realizedCost: 80000,
    openCommitments: 120000, estimatedCostToComplete: 860000,
    plannedProgress: 0, physicalProgress: 0,
    scheduleDelayDays: 0, dailyWorkHours: 8,
    ownTeamProgress: 0, currentStage: "Mobilização", currentStageProgress: 15,
    currentProcess: "Implantação do canteiro, locação dos eixos e preparação dos acessos provisórios.",
    currentScope: "Preparação do canteiro e planejamento da implantação das fundações do galpão.",
    totalPlannedDays: 164, nextMilestone: "Liberar implantação e locação das fundações",
    nextMilestoneDate: "2026-08-14", riskLevel: "Normal", cnoStatus: "A inscrever",
    cprbMode: "A parametrizar", channel: "obra.teste02@betaconstrutora.com.br",
    documentsUrl: docs("obra-002"),
  }),
  demo("works", "Reforma Administrativa — Obra Teste", "TST-OBR-003", "Pausada", "2026-06-02", 310000, {
    code: "TST-OBR-003", cno: "22.222.22222/22", name: "Reforma Administrativa — Obra Teste", client: "Cliente Demonstração Gama",
    constructionType: "Reforma",
    city: "Salvador/BA", costCenter: "CC-TESTE-003", manager: "Gestor Teste 03",
    foreman: "Encarregado Teste 03", status: "Pausada", startDate: "2026-06-02",
    endDate: "2026-11-30", budget: 310000, realizedCost: 240000,
    openCommitments: 40000, estimatedCostToComplete: 100000,
    plannedProgress: 50, physicalProgress: 42,
    scheduleDelayDays: 14, dailyWorkHours: 8,
    ownTeamProgress: 46, currentStage: "Acabamentos", currentStageProgress: 30,
    currentProcess: "Regularização das paredes, instalação de forros e preparação das superfícies para pintura.",
    currentScope: "Adequação das salas administrativas e regularização das instalações de climatização.",
    totalPlannedDays: 181, nextMilestone: "Retomar acabamentos do pavimento térreo",
    nextMilestoneDate: "2026-08-12", riskLevel: "Crítico",
    scheduleNotes: "Obra pausada aguardando liberação técnica do cliente.",
    cnoStatus: "Paralisado",
    cprbMode: "A parametrizar", documentsUrl: docs("obra-003"),
  }),

  demo("worklogs", "Alvenaria do bloco A — apontamento fictício", "TST-RDO-001", "Validado", "2026-07-21", 0, {
    logId: "TST-RDO-001", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-21", shift: "Integral", currentStage: "Alvenaria",
    currentActivity: "Marcação e primeira fiada das paredes do bloco A — cenário fictício.",
    productivityStatus: "Produtivo", lostHours: 0, unproductiveCause: "Não se aplica",
    conditionDetail: "Frente liberada e materiais disponíveis.", ownTeamCount: 17,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 1, progressPercentAfter: 14, weatherCondition: "Ensolarado",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Elevação de paredes — apontamento fictício", "TST-RDO-002", "Validado", "2026-07-22", 0, {
    logId: "TST-RDO-002", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-22", shift: "Integral", currentStage: "Alvenaria",
    currentActivity: "Elevação das paredes dos apartamentos 101 a 104 — cenário fictício.",
    productivityStatus: "Produtivo", lostHours: 0, unproductiveCause: "Não se aplica",
    conditionDetail: "Produção dentro da meta diária.", ownTeamCount: 18,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 1, progressPercentAfter: 15, weatherCondition: "Nublado",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Betoneira indisponível — apontamento fictício", "TST-RDO-003", "Validado", "2026-07-23", 0, {
    logId: "TST-RDO-003", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-23", shift: "Integral", currentStage: "Alvenaria",
    currentActivity: "Alvenaria do corredor central e preparação das vergas — cenário fictício.",
    productivityStatus: "Parcialmente improdutivo", lostHours: 4,
    unproductiveCause: "Maquinário quebrado",
    conditionDetail: "Betoneira parou por falha elétrica; produção retomada após manutenção corretiva.",
    affectedEquipment: "Betoneira 400 L — TESTE", ownTeamCount: 18,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 0.5, progressPercentAfter: 15.5, weatherCondition: "Ensolarado",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Tubulação embutida — apontamento fictício", "TST-RDO-004", "Validado", "2026-07-24", 0, {
    logId: "TST-RDO-004", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-24", shift: "Integral", currentStage: "Instalações",
    currentActivity: "Abertura de rasgos e passagem das tubulações elétricas do bloco A — cenário fictício.",
    productivityStatus: "Produtivo", lostHours: 0, unproductiveCause: "Não se aplica",
    conditionDetail: "Execução conforme planejamento.", ownTeamCount: 18,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 1, progressPercentAfter: 16.5, weatherCondition: "Ensolarado",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Chuva impediu concretagem — apontamento fictício", "TST-RDO-005", "Validado", "2026-07-25", 0, {
    logId: "TST-RDO-005", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-25", shift: "Integral", currentStage: "Estrutura",
    currentActivity: "Concretagem das vergas e contravergas do bloco A — cenário fictício.",
    productivityStatus: "Improdutivo", lostHours: 8, unproductiveCause: "Chuva",
    conditionDetail: "Chuva forte durante todo o turno impediu concretagem e movimentação segura de materiais.",
    ownTeamCount: 16, contractorCount: 10, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 0, progressPercentAfter: 16.5, weatherCondition: "Chuva forte",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Operador ausente — apontamento fictício", "TST-RDO-006", "Validado", "2026-07-26", 0, {
    logId: "TST-RDO-006", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-26", shift: "Integral", currentStage: "Alvenaria",
    currentActivity: "Transporte de blocos e continuidade da alvenaria do pavimento térreo — cenário fictício.",
    productivityStatus: "Parcialmente improdutivo", lostHours: 3,
    unproductiveCause: "Operador ausente",
    conditionDetail: "Ausência do operador do manipulador telescópico reduziu o abastecimento das frentes.",
    absentOperator: "Operador de manipulador telescópico", ownTeamCount: 17,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 0.5, progressPercentAfter: 17, weatherCondition: "Nublado",
    responsible: "Engenharia Teste", status: "Validado",
  }),
  demo("worklogs", "Alvenaria e tubulações — apontamento fictício", "TST-RDO-007", "Validado", "2026-07-27", 0, {
    logId: "TST-RDO-007", workCode: "TST-OBR-001", work: "Residencial Horizonte — Obra Teste",
    date: "2026-07-27", shift: "Integral", currentStage: "Alvenaria",
    currentActivity: "Elevação da alvenaria do bloco A e passagem das primeiras tubulações elétricas embutidas.",
    productivityStatus: "Produtivo", lostHours: 0, unproductiveCause: "Não se aplica",
    conditionDetail: "Meta diária atingida após redistribuição das equipes.", ownTeamCount: 18,
    contractorCount: 12, contractorCompany: "Alvenaria Modelo Ltda. — TESTE",
    progressDelta: 1, progressPercentAfter: 18, weatherCondition: "Ensolarado",
    responsible: "Engenharia Teste", status: "Validado",
  }),

  demo("suppliers", "Cimento Modelo Comércio Ltda. — TESTE", "TST-FOR-001", "Ativo", "2027-01-31", 0, {
    code: "TST-FOR-001", cnpj: "00.000.000/0001-00", companyName: "Cimento Modelo Comércio Ltda. — TESTE",
    tradeName: "Cimento Modelo", category: "Cimento e argamassa", contact: "Contato Teste 01",
    phone: "(00) 00000-0001", email: "fornecedor01@example.com", city: "Campinas/SP",
    bankValidated: "Sim", documentValidity: "2027-01-31", status: "Ativo", rating: 5,
    documentsUrl: docs("fornecedor-001"),
  }),
  demo("suppliers", "Locadora Exemplo Equipamentos Ltda. — TESTE", "TST-FOR-002", "Em validação", "2026-09-15", 0, {
    code: "TST-FOR-002", cnpj: "11.111.111/0001-11", companyName: "Locadora Exemplo Equipamentos Ltda. — TESTE",
    tradeName: "Locadora Exemplo", category: "Locação de máquinas", contact: "Contato Teste 02",
    phone: "(00) 00000-0002", email: "fornecedor02@example.com", city: "Hortolândia/SP",
    bankValidated: "Em validação", documentValidity: "2026-09-15", status: "Em validação", rating: 4,
    documentsUrl: docs("fornecedor-002"),
  }),
  demo("suppliers", "Refeições Demonstração S.A. — TESTE", "TST-FOR-003", "Ativo", "2027-03-10", 0, {
    code: "TST-FOR-003", cnpj: "22.222.222/0001-22", companyName: "Refeições Demonstração S.A. — TESTE",
    tradeName: "Refeições Demonstração", category: "Alimentação", contact: "Contato Teste 03",
    phone: "(00) 00000-0003", email: "fornecedor03@example.com", city: "Campinas/SP",
    bankValidated: "Sim", documentValidity: "2027-03-10", status: "Ativo", rating: 4,
    documentsUrl: docs("fornecedor-003"),
  }),

  demo("expenses", "Compra fictícia de cimento e argamassa", "TST-PAG-001", "Aguardando validação", "2026-08-05", 12850.4, {
    accountId: "TST-PAG-001", supplierCode: "TST-FOR-001", supplier: "Cimento Modelo Comércio Ltda. — TESTE",
    work: "Residencial Horizonte — Obra Teste", costCenter: "CC-TESTE-001", category: "Materiais",
    description: "Compra fictícia de cimento e argamassa", issueDate: "2026-07-27", dueDate: "2026-08-05",
    expectedAmount: 12850.4, approval: "Pendente", status: "Aguardando validação",
    invoiceUrl: docs("nf-pag-001"), responsible: "Financeiro Teste",
  }),
  demo("expenses", "Locação mensal fictícia de escavadeira", "TST-PAG-002", "Aguardando validação", "2026-08-02", 18400, {
    accountId: "TST-PAG-002", supplierCode: "TST-FOR-002", supplier: "Locadora Exemplo Equipamentos Ltda. — TESTE",
    work: "Galpão Industrial Modelo — Obra Teste", costCenter: "CC-TESTE-002", category: "Locação",
    description: "Locação mensal fictícia de escavadeira", issueDate: "2026-07-25", dueDate: "2026-08-02",
    expectedAmount: 18400, approval: "Aprovada", status: "Aguardando validação",
    invoiceUrl: docs("nf-pag-002"), responsible: "Financeiro Teste",
  }),
  demo("expenses", "Internet do alojamento — lançamento fictício", "TST-PAG-003", "Pago", "2026-07-20", 189.9, {
    accountId: "TST-PAG-003", supplier: "Operadora Exemplo — TESTE", work: "Residencial Horizonte — Obra Teste",
    costCenter: "CC-TESTE-001", category: "Internet", description: "Internet do alojamento — lançamento fictício",
    issueDate: "2026-07-10", dueDate: "2026-07-20", expectedAmount: 189.9, approval: "Aprovada",
    status: "Pago", paymentDate: "2026-07-18", paidAmount: 189.9, invoiceUrl: docs("nf-pag-003"),
    receiptUrl: docs("comprovante-pag-003"), responsible: "Financeiro Teste",
  }),

  demo("cards", "Combustível — compra fictícia", "TST-CC-001", "Conferida", "2026-07-24", 426.73, {
    expenseId: "TST-CC-001", date: "2026-07-24", holder: "Titular Teste 01", cardEnding: "0001",
    merchant: "Posto Demonstração", description: "Combustível — compra fictícia",
    work: "Residencial Horizonte — Obra Teste", category: "Combustível", amount: 426.73,
    billingPeriod: "2026-07-01", documentUrl: docs("recibo-cartao-001"), approval: "Aprovada",
    status: "Conferida", responsible: "Financeiro Teste",
  }),
  demo("cards", "Material elétrico — compra fictícia", "TST-CC-002", "Documento pendente", "2026-07-26", 785.2, {
    expenseId: "TST-CC-002", date: "2026-07-26", holder: "Titular Teste 02", cardEnding: "0002",
    merchant: "Elétrica Exemplo", description: "Material elétrico — compra fictícia",
    work: "Galpão Industrial Modelo — Obra Teste", category: "Materiais", amount: 785.2,
    billingPeriod: "2026-07-01", approval: "Pendente", status: "Documento pendente",
    responsible: "Financeiro Teste",
  }),
  demo("cards", "Hospedagem emergencial — compra fictícia", "TST-CC-003", "Paga", "2026-07-15", 640, {
    expenseId: "TST-CC-003", date: "2026-07-15", holder: "Titular Teste 01", cardEnding: "0001",
    merchant: "Hotel Modelo", description: "Hospedagem emergencial — compra fictícia",
    work: "Reforma Administrativa — Obra Teste", category: "Hospedagem", amount: 640,
    billingPeriod: "2026-07-01", documentUrl: docs("recibo-cartao-003"), approval: "Aprovada",
    status: "Paga", responsible: "Financeiro Teste",
  }),

  demo("rentals", "Rua Modelo, 100 — Alojamento TESTE", "TST-IMO-001", "Ativo", "2027-02-28", 3280, {
    propertyId: "TST-IMO-001", work: "Residencial Horizonte — Obra Teste",
    address: "Rua Modelo, 100 — Alojamento TESTE", city: "Campinas/SP",
    landlord: "Proprietário Fictício 01", contract: "TST-CTR-001", startDate: "2026-07-01",
    endDate: "2027-02-28", monthlyRent: 2500, capacity: 8, occupants: 6,
    residentNames: "Colaborador Teste 01\nColaborador Teste 02\nColaborador Teste 03\nColaborador Teste 04\nColaborador Teste 05\nColaborador Teste 06",
    waterPayee: "Concessionária Exemplo Água", water: 180, energyPayee: "Concessionária Exemplo Energia",
    energy: 410, internetPayee: "Operadora Exemplo", internet: 190, totalMonthly: 3280,
    status: "Ativo", contractUrl: docs("contrato-imovel-001"),
  }),
  demo("rentals", "Avenida Demonstração, 250 — Casa TESTE", "TST-IMO-002", "Em contratação", "2027-04-30", 2670, {
    propertyId: "TST-IMO-002", work: "Galpão Industrial Modelo — Obra Teste",
    address: "Avenida Demonstração, 250 — Casa TESTE", city: "Hortolândia/SP",
    landlord: "Imobiliária Fictícia Ltda.", contract: "TST-CTR-002", startDate: "2026-08-01",
    endDate: "2027-04-30", monthlyRent: 2100, capacity: 6, occupants: 4,
    residentNames: "Colaborador Teste 07\nColaborador Teste 08\nColaborador Teste 09\nColaborador Teste 10",
    waterPayee: "Concessionária Exemplo Água", water: 140, energyPayee: "Concessionária Exemplo Energia",
    energy: 280, internetPayee: "Operadora Exemplo", internet: 150, totalMonthly: 2670,
    status: "Em contratação", contractUrl: docs("contrato-imovel-002"),
  }),
  demo("rentals", "Travessa Cenário, 45 — Imóvel TESTE", "TST-IMO-003", "A encerrar", "2026-08-15", 1960, {
    propertyId: "TST-IMO-003", work: "Reforma Administrativa — Obra Teste",
    address: "Travessa Cenário, 45 — Imóvel TESTE", city: "Salvador/BA",
    landlord: "Proprietário Fictício 03", contract: "TST-CTR-003", startDate: "2026-05-15",
    endDate: "2026-08-15", monthlyRent: 1500, capacity: 4, occupants: 2,
    residentNames: "Colaborador Teste 11\nColaborador Teste 12", waterPayee: "Concessionária Exemplo Água",
    water: 110, energyPayee: "Concessionária Exemplo Energia", energy: 240,
    internetPayee: "Operadora Exemplo", internet: 110, totalMonthly: 1960,
    status: "A encerrar", contractUrl: docs("contrato-imovel-003"),
  }),

  demo("assets", "Escavadeira Modelo 320 — TESTE", "TST-ATV-001", "Em uso", "2026-08-10", 18400, {
    assetId: "TST-ATV-001", type: "Máquina", description: "Escavadeira Modelo 320 — TESTE",
    serial: "SERIE-TESTE-001", ownership: "Locado", rentalCompany: "Locadora Exemplo Equipamentos Ltda. — TESTE",
    work: "Galpão Industrial Modelo — Obra Teste", responsible: "Operador Teste 01",
    startDate: "2026-07-10", rentalEndDate: "2026-08-08", rentalPeriodDays: 30,
    dueDate: "2026-07-31", paymentStatus: "Parcial", paidAmount: 9200,
    nextMaintenance: "2026-08-10", meter: 128, idleDays: 0,
    preventiveCost: 950, correctiveCost: 0, monthlyCost: 18400, status: "Em uso",
    documentsUrl: docs("ativo-001"),
  }),
  demo("assets", "Betoneira 400 L — TESTE", "TST-ATV-002", "Ocioso", "2026-08-05", 1850, {
    assetId: "TST-ATV-002", type: "Equipamento", description: "Betoneira 400 L — TESTE",
    serial: "SERIE-TESTE-002", ownership: "Próprio", work: "Residencial Horizonte — Obra Teste",
    responsible: "Encarregado Teste 01", startDate: "2026-05-01", nextMaintenance: "2026-08-05",
    rentalPeriodDays: 30, paymentStatus: "Não se aplica", meter: 340,
    idleSince: "2026-07-20", idleDays: 8, preventiveCost: 420,
    correctiveCost: 680, monthlyCost: 1850, status: "Ocioso", documentsUrl: docs("ativo-002"),
  }),
  demo("assets", "Veículo Utilitário — TESTE", "TST-ATV-003", "Em manutenção", "2026-07-30", 3850, {
    assetId: "TST-ATV-003", type: "Veículo", description: "Veículo Utilitário — TESTE",
    serial: "AAA0T00", ownership: "Locado", rentalCompany: "Frota Demonstração Ltda.",
    work: "Reforma Administrativa — Obra Teste", responsible: "Motorista Teste 01",
    startDate: "2026-07-01", rentalEndDate: "2026-07-30", rentalPeriodDays: 30,
    dueDate: "2026-07-30", paymentStatus: "Pago", paidAmount: 3850,
    paymentDate: "2026-07-24", nextMaintenance: "2026-07-30", meter: 18420,
    idleSince: "2026-07-25", idleDays: 3, preventiveCost: 600, correctiveCost: 1450,
    monthlyCost: 3850, status: "Em manutenção", documentsUrl: docs("ativo-003"),
  }),
  demo("assets", "Guindaste Telescópico 35 t — TESTE", "TST-ATV-004", "Ocioso", "2026-07-31", 60000, {
    assetId: "TST-ATV-004", type: "Máquina", description: "Guindaste Telescópico 35 t — TESTE",
    serial: "SERIE-TESTE-004", ownership: "Locado", rentalCompany: "Locadora Modelo Pesados Ltda. — TESTE",
    work: "Residencial Horizonte — Obra Teste", responsible: "Operador Teste 04",
    startDate: "2026-07-01", rentalEndDate: "2026-07-30", rentalPeriodDays: 30,
    dueDate: "2026-07-31", paymentStatus: "Pendente", paidAmount: 0,
    nextMaintenance: "2026-08-15", meter: 72, idleSince: "2026-07-21", idleDays: 3,
    preventiveCost: 0, correctiveCost: 0, monthlyCost: 60000, status: "Ocioso",
    documentsUrl: docs("ativo-004"),
  }),
  demo("assets", "Retroescavadeira JCB 3CX — TESTE", "TST-ATV-005", "Em manutenção", "2026-07-31", 30000, {
    assetId: "TST-ATV-005", type: "Máquina", description: "Retroescavadeira JCB 3CX — TESTE",
    serial: "SERIE-TESTE-005", ownership: "Locado", rentalCompany: "Locadora Modelo Linha Amarela Ltda. — TESTE",
    work: "Residencial Horizonte — Obra Teste", responsible: "Operador Teste 05",
    startDate: "2026-07-01", rentalEndDate: "2026-07-30", rentalPeriodDays: 30,
    dueDate: "2026-07-31", paymentStatus: "Pendente", paidAmount: 0,
    nextMaintenance: "2026-07-31", meter: 214, idleSince: "2026-07-27", idleDays: 4,
    currentActivity: "Aguardando conclusão do reparo hidráulico para retornar à escavação das valas.",
    preventiveCost: 0, correctiveCost: 6850, monthlyCost: 30000, status: "Em manutenção",
    documentsUrl: docs("ativo-005"),
  }),
  demo("assets", "Pá Carregadeira Volvo L60H — TESTE", "TST-ATV-006", "Em uso", "2026-08-20", 45000, {
    assetId: "TST-ATV-006", type: "Máquina", description: "Pá Carregadeira Volvo L60H — TESTE",
    serial: "SERIE-TESTE-006", ownership: "Locado", rentalCompany: "Locadora Modelo Linha Amarela Ltda. — TESTE",
    work: "Residencial Horizonte — Obra Teste", responsible: "Operador Teste 06",
    startDate: "2026-07-01", rentalEndDate: "2026-07-30", rentalPeriodDays: 30,
    dueDate: "2026-07-10", paymentStatus: "Pago", paidAmount: 45000,
    paymentDate: "2026-07-08", nextMaintenance: "2026-08-20", meter: 186,
    idleDays: 0, currentActivity: "Ativa e produzindo na movimentação de agregados e abastecimento das frentes.",
    preventiveCost: 0, correctiveCost: 0, monthlyCost: 45000, status: "Em uso",
    documentsUrl: docs("ativo-006"),
  }),

  demo("asset_events", "Paralisação do guindaste por chuva — TESTE", "TST-OCO-001", "Encerrada", "2026-07-21", 0, {
    occurrenceId: "TST-OCO-001", assetName: "Guindaste Telescópico 35 t — TESTE",
    assetId: "TST-ATV-004", work: "Residencial Horizonte — Obra Teste",
    occurrenceTitle: "Paralisação do guindaste por chuva — TESTE",
    eventType: "Ociosidade", cause: "Chuva", startDate: "2026-07-21",
    endDate: "2026-07-23", idleDays: 3, rentalValue: 60000,
    rentalPeriodDays: 30, dailyRentalRate: 2000, estimatedDowntimeLoss: 6000,
    whatHappened: "Chuva intensa e solo sem condição segura para estabilização do equipamento.",
    correctionDescription: "Operação retomada após inspeção do terreno e liberação da segurança.",
    maintenanceCost: 0, paymentStatus: "Não se aplica", paidAmount: 0,
    status: "Encerrada", documentUrl: docs("ocorrencia-maquina-001"),
  }),
  demo("asset_events", "Correção do sistema hidráulico da escavadeira — TESTE", "TST-OCO-002", "Em correção", "2026-07-24", 4200, {
    occurrenceId: "TST-OCO-002", assetName: "Escavadeira Modelo 320 — TESTE",
    assetId: "TST-ATV-001", work: "Galpão Industrial Modelo — Obra Teste",
    occurrenceTitle: "Correção do sistema hidráulico da escavadeira — TESTE",
    eventType: "Manutenção corretiva", cause: "Maquinário quebrado",
    startDate: "2026-07-24", endDate: "2026-07-25", idleDays: 2,
    rentalValue: 18400, rentalPeriodDays: 30, dailyRentalRate: 613.33,
    estimatedDowntimeLoss: 1226.67,
    whatHappened: "Perda de pressão e vazamento identificado no circuito hidráulico.",
    correctionDescription: "Troca de mangueira, vedação e teste de pressão em andamento.",
    maintenanceSupplier: "Oficina Hidráulica Demonstração Ltda. — TESTE",
    maintenanceCost: 4200, paymentStatus: "Parcial", paidAmount: 2000,
    dueDate: "2026-08-05", status: "Em correção",
    documentUrl: docs("ocorrencia-maquina-002"),
  }),
  demo("asset_events", "Reparo elétrico da betoneira — TESTE", "TST-OCO-003", "Concluída", "2026-07-20", 680, {
    occurrenceId: "TST-OCO-003", assetName: "Betoneira 400 L — TESTE",
    assetId: "TST-ATV-002", work: "Residencial Horizonte — Obra Teste",
    occurrenceTitle: "Reparo elétrico da betoneira — TESTE",
    eventType: "Manutenção corretiva", cause: "Maquinário quebrado",
    startDate: "2026-07-20", endDate: "2026-07-27", idleDays: 8,
    rentalValue: 1850, rentalPeriodDays: 30, dailyRentalRate: 61.67,
    estimatedDowntimeLoss: 493.33,
    whatHappened: "Falha no conjunto elétrico impediu o acionamento do motor.",
    correctionDescription: "Contator e cabeamento substituídos; equipamento testado.",
    maintenanceSupplier: "Elétrica Industrial Modelo — TESTE",
    maintenanceCost: 680, paymentStatus: "Pago", paidAmount: 680,
    dueDate: "2026-07-26", paymentDate: "2026-07-25", status: "Concluída",
    documentUrl: docs("ocorrencia-maquina-003"),
  }),
  demo("asset_events", "Reparo da bomba hidráulica da retroescavadeira — TESTE", "TST-OCO-005", "Em correção", "2026-07-27", 6850, {
    occurrenceId: "TST-OCO-005", assetName: "Retroescavadeira JCB 3CX — TESTE",
    assetId: "TST-ATV-005", work: "Residencial Horizonte — Obra Teste",
    occurrenceTitle: "Reparo da bomba hidráulica da retroescavadeira — TESTE",
    eventType: "Manutenção corretiva", cause: "Maquinário quebrado",
    startDate: "2026-07-27", endDate: "2026-07-31", idleDays: 4,
    rentalValue: 30000, rentalPeriodDays: 30, dailyRentalRate: 1000,
    estimatedDowntimeLoss: 4000,
    whatHappened: "Queda de pressão no sistema hidráulico interrompeu a escavação e a movimentação de solo.",
    correctionDescription: "Substituição do kit de vedação, revisão da bomba hidráulica e teste de pressão antes da liberação.",
    maintenanceSupplier: "Oficina Hidráulica Modelo Ltda. — TESTE",
    maintenanceCost: 6850, paymentStatus: "Pendente", paidAmount: 0,
    dueDate: "2026-08-05", status: "Em correção",
    documentUrl: docs("ocorrencia-maquina-005"),
  }),
  demo("asset_events", "Manutenção do veículo utilitário — TESTE", "TST-OCO-004", "Aberta", "2026-07-25", 1450, {
    occurrenceId: "TST-OCO-004", assetName: "Veículo Utilitário — TESTE",
    assetId: "TST-ATV-003", work: "Reforma Administrativa — Obra Teste",
    occurrenceTitle: "Manutenção do veículo utilitário — TESTE",
    eventType: "Manutenção preventiva", cause: "Manutenção programada",
    startDate: "2026-07-25", endDate: "2026-07-27", idleDays: 3,
    rentalValue: 3850, rentalPeriodDays: 30, dailyRentalRate: 128.33,
    estimatedDowntimeLoss: 385,
    whatHappened: "Veículo retirado da operação para revisão programada.",
    correctionDescription: "Troca de óleo, filtros, pastilhas e inspeção dos freios.",
    maintenanceSupplier: "Centro Automotivo Demonstração — TESTE",
    maintenanceCost: 1450, paymentStatus: "Pendente", paidAmount: 0,
    dueDate: "2026-08-02", status: "Aberta",
    documentUrl: docs("ocorrencia-maquina-004"),
  }),

  demo("people", "Colaborador Teste 01", "TST-COL-001", "Ativo", "2026-05-05", 4850, {
    employeeCode: "TST-COL-001", registration: "MAT-TST-001", name: "Colaborador Teste 01",
    role: "Encarregado de obra", department: "Operações", work: "Residencial Horizonte — Obra Teste",
    manager: "Gestor Teste 01", admissionDate: "2026-05-05", salary: 3500, benefits: 1350,
    monthlyCost: 4850, status: "Ativo", corporateEmail: "colaborador.teste01@betaconstrutora.com.br",
    accessProfile: "Gestor de obra", documentsUrl: docs("colaborador-001"),
  }),
  demo("people", "Colaborador Teste 02", "TST-COL-002", "Férias", "2025-11-10", 3620, {
    employeeCode: "TST-COL-002", registration: "MAT-TST-002", name: "Colaborador Teste 02",
    role: "Ajudante geral", department: "Operações", work: "Residencial Horizonte — Obra Teste",
    manager: "Encarregado Teste 01", admissionDate: "2025-11-10", salary: 2400, benefits: 1220,
    monthlyCost: 3620, status: "Férias", corporateEmail: "colaborador.teste02@betaconstrutora.com.br",
    accessProfile: "Sem acesso administrativo", documentsUrl: docs("colaborador-002"),
  }),
  demo("people", "Colaborador Teste 03", "TST-COL-003", "Desligado", "2025-08-01", 4180, {
    employeeCode: "TST-COL-003", registration: "MAT-TST-003", name: "Colaborador Teste 03",
    role: "Eletricista", department: "Operações", work: "Reforma Administrativa — Obra Teste",
    manager: "Encarregado Teste 03", admissionDate: "2025-08-01", salary: 3000, benefits: 1180,
    monthlyCost: 4180, status: "Desligado", terminationDate: "2026-07-18",
    terminationReason: "Encerramento de contrato — cenário fictício",
    corporateEmail: "colaborador.teste03@betaconstrutora.com.br", accessProfile: "Acesso encerrado",
    documentsUrl: docs("colaborador-003"),
  }),
  demo("terminations", "Colaborador Teste 03", "TST-RES-001", "Prévia — não transmitida", "2026-07-18", 7279.12, {
    terminationCode: "TST-RES-001", employeeName: "Colaborador Teste 03",
    employeeCode: "TST-COL-003", role: "Eletricista", admissionDate: "2025-08-01",
    terminationDate: "2026-07-18", deathDate: "", deathKnowledgeDate: "",
    deathRelatedToWork: "Não", catNumber: "", deathPaymentRecipient: "DECEASED_CPF",
    contractType: "Prazo determinado", expectedContractEnd: "2026-07-18",
    reciprocalEarlyTerminationClause: "Não", projectedTerminationDate: "2026-07-18",
    terminationType: "FIXED_TERM_END", terminationTypeLabel: "Término normal de contrato a prazo",
    esocialReasonCode: "06", noticeType: "NOT_APPLICABLE", noticeTypeLabel: "Não se aplica",
    noticeDays: 0, noticeProjectionDays: 0, baseSalary: 3000, variableAverage: 0, remunerationBase: 3000,
    salaryBalance: 1800, noticeAmount: 0, thirteenthBaseMonths: 7,
    thirteenthNoticeMonths: 0, thirteenthBaseSalary: 1750,
    thirteenthNoticeSalary: 0, thirteenthSalary: 1750,
    accruedVacation: 0, proportionalVacation: 3000, vacationThird: 1000,
    fixedTermIndemnity: 0, grossAmount: 7550, inss: 270.88, irrf: 0,
    noticeDeduction: 0, totalDeductions: 270.88, netAmount: 7279.12,
    fgtsMonthlyBase: 1800, fgtsThirteenthBase: 1750, fgtsNoticeBase: 0,
    fgtsMonthlyDeposit: 144, fgtsThirteenthDeposit: 140, fgtsNoticeDeposit: 0,
    fgtsSeveranceDeposit: 284, fgtsFine: 0, employerSocialCharges: 986.9,
    employerCost: 8820.9, payrollHistoryCount: 0,
    rulesVersion: "BR-RESCISAO-2026.2",
    mosVersion: "MOS eSocial S-1.3 consolidado até a NO 11/2026 — retificado em 28/05/2026",
    layoutVersion: "Leiautes eSocial S-1.3 — NT 06/2026, revisão de 09/04/2026",
    esocialDeadlineBaseDate: "2026-07-28", paymentDeadlineBaseDate: "2026-07-28",
    esocialIndApurIR: "0", esocialPaymentEvent: "S-1210",
    resultHash: "HASH-FICTICIO-RESCISAO-NAO-TRANSMITIDA",
    esocialStatus: "Não transmitido — prévia", fgtsCheckStatus: "Pendente",
    status: "Prévia — não transmitida",
  }),

  demo("food", "Almoço — registro fictício", "TST-ALI-001", "Conferido", "2026-07-27", 720, {
    entryId: "TST-ALI-001", date: "2026-07-27", work: "Residencial Horizonte — Obra Teste",
    supplierCode: "TST-FOR-003", supplier: "Refeições Demonstração S.A. — TESTE", meal: "Almoço",
    expectedQty: 30, deliveredQty: 30, takenQty: 30, whoTook: "Equipe Teste A — 30 pessoas",
    notTaken: "Ninguém", unitPrice: 24, expectedTotal: 720, billedTotal: 720,
    status: "Conferido", invoiceUrl: docs("nf-alimentacao-001"), responsible: "Encarregado Teste 01",
  }),
  demo("food", "Café da manhã — registro fictício", "TST-ALI-002", "Divergência", "2026-07-27", 323, {
    entryId: "TST-ALI-002", date: "2026-07-27", work: "Galpão Industrial Modelo — Obra Teste",
    supplierCode: "TST-FOR-003", supplier: "Refeições Demonstração S.A. — TESTE", meal: "Café da manhã",
    expectedQty: 20, deliveredQty: 19, takenQty: 17, whoTook: "Equipe Teste B — 17 pessoas",
    notTaken: "2 refeições não retiradas e 1 não entregue", unitPrice: 17, expectedTotal: 340,
    billedTotal: 323, status: "Divergência", invoiceUrl: docs("nf-alimentacao-002"),
    responsible: "Encarregado Teste 02",
  }),
  demo("food", "Jantar — registro fictício", "TST-ALI-003", "Em conferência", "2026-07-26", 456, {
    entryId: "TST-ALI-003", date: "2026-07-26", work: "Reforma Administrativa — Obra Teste",
    supplierCode: "TST-FOR-003", supplier: "Refeições Demonstração S.A. — TESTE", meal: "Jantar",
    expectedQty: 12, deliveredQty: 12, takenQty: 11, whoTook: "Equipe Teste C — 11 pessoas",
    notTaken: "Colaborador Teste 03 não retirou", unitPrice: 38, expectedTotal: 456,
    billedTotal: 456, status: "Em conferência", invoiceUrl: docs("nf-alimentacao-003"),
    responsible: "Encarregado Teste 03",
  }),

  demo("taxes", "INSS — obrigação fictícia", "TST-IMP-001", "Pendente", "2026-08-20", 18450.75, {
    taxId: "TST-IMP-001", tax: "INSS — obrigação fictícia", entity: "00.000.000/0001-00",
    period: "2026-07-01", dueDate: "2026-08-20", expectedAmount: 18450.75,
    guideReceived: "Sim", guideUrl: docs("guia-imposto-001"), status: "Pendente",
    responsible: "Fiscal Teste",
  }),

  demo("contractors", "Alvenaria Modelo Ltda. — TESTE", "TST-MED-001", "Em conferência", "2026-07-26", 48600, {
    measurementId: "TST-MED-001", companyName: "Alvenaria Modelo Ltda. — TESTE",
    cnpj: "33.333.333/0001-33", workCode: "TST-OBR-001",
    work: "Residencial Horizonte — Obra Teste",
    cno: "00.000.00000/00", contractNumber: "CONT-TST-010",
    service: "Execução de alvenaria — cenário fictício",
    currentActivity: "Elevação das paredes do bloco A e preparação das vergas.",
    workerCount: 12, contractValue: 240000, scopeWeight: 24,
    plannedProgress: 32, executionProgress: 27, productivityStatus: "Atenção",
    delayReason: "Perda de produção por chuva e indisponibilidade pontual de betoneira.",
    expectedCompletion: "2026-10-18", lastProgressUpdate: "2026-07-27",
    measurementNumber: "MED-03", measurementDate: "2026-07-26",
    measuredAmount: 48600, retentionInss: 5346, retentionIss: 972,
    netAmount: 42282, status: "Em conferência", invoiceUrl: docs("nf-medicao-001"),
    measurementUrl: docs("medicao-001"), contractUrl: docs("contrato-sub-001"),
    responsible: "Engenharia Teste",
  }),
  demo("contractors", "Instalações Exemplo S.A. — TESTE", "TST-MED-002", "Aguardando aprovação", "2026-07-27", 31750, {
    measurementId: "TST-MED-002", companyName: "Instalações Exemplo S.A. — TESTE",
    cnpj: "44.444.444/0001-44", workCode: "TST-OBR-002",
    work: "Galpão Industrial Modelo — Obra Teste",
    cno: "11.111.11111/11", contractNumber: "CONT-TST-014",
    service: "Instalações elétricas — cenário fictício",
    currentActivity: "Planejamento executivo e mobilização da equipe elétrica.",
    workerCount: 7, contractValue: 180000, scopeWeight: 18,
    plannedProgress: 4, executionProgress: 2, productivityStatus: "No ritmo",
    expectedCompletion: "2026-12-18", lastProgressUpdate: "2026-07-27",
    measurementNumber: "MED-01", measurementDate: "2026-07-27",
    measuredAmount: 31750, retentionInss: 0, retentionIss: 635,
    netAmount: 31115, status: "Aguardando aprovação",
    measurementUrl: docs("medicao-002"), contractUrl: docs("contrato-sub-002"),
    responsible: "Engenharia Teste",
  }),
  demo("taxes", "FGTS — obrigação fictícia", "TST-IMP-002", "Aguardando aprovação", "2026-08-07", 9320.6, {
    taxId: "TST-IMP-002", tax: "FGTS — obrigação fictícia", entity: "00.000.000/0001-00",
    period: "2026-07-01", dueDate: "2026-08-07", expectedAmount: 9320.6,
    guideReceived: "Sim", guideUrl: docs("guia-imposto-002"), status: "Aguardando aprovação",
    responsible: "Fiscal Teste",
  }),
  demo("taxes", "ISS — obrigação fictícia", "TST-IMP-003", "Pago", "2026-07-15", 4780, {
    taxId: "TST-IMP-003", tax: "ISS — obrigação fictícia", entity: "00.000.000/0001-00",
    period: "2026-06-01", dueDate: "2026-07-15", expectedAmount: 4780,
    guideReceived: "Sim", guideUrl: docs("guia-imposto-003"), status: "Pago",
    paymentDate: "2026-07-14", paidAmount: 4780, receiptUrl: docs("comprovante-imposto-003"),
    responsible: "Fiscal Teste",
  }),

  demo("purchases", "Cimento CP-II — solicitação fictícia", "TST-CMP-001", "Aguardando análise", "2026-07-27", 9800, {
    requestId: "TST-CMP-001", requestDate: "2026-07-27", work: "Residencial Horizonte — Obra Teste",
    requester: "Encarregado Teste 01", material: "Cimento CP-II — solicitação fictícia",
    quantity: 200, unit: "saco", neededDate: "2026-08-03", priority: "Alta",
    minimumQuotes: 3, quotesReceived: 2, supplier: "Em definição", totalAmount: 9800,
    approval: "Pendente", status: "Aguardando análise", documentsUrl: docs("compra-001"),
  }),
  demo("purchases", "Cabos elétricos — solicitação fictícia", "TST-CMP-002", "Aguardando análise", "2026-07-25", 7240.5, {
    requestId: "TST-CMP-002", requestDate: "2026-07-25", work: "Galpão Industrial Modelo — Obra Teste",
    requester: "Encarregado Teste 02", material: "Cabos elétricos — solicitação fictícia",
    quantity: 850, unit: "metro", neededDate: "2026-08-05", priority: "Média",
    minimumQuotes: 3, quotesReceived: 3, supplier: "Elétrica Exemplo", totalAmount: 7240.5,
    approval: "Pendente", status: "Aguardando análise", documentsUrl: docs("compra-002"),
  }),
  demo("purchases", "Tijolos cerâmicos — compra fictícia", "TST-CMP-003", "Aprovado", "2026-07-18", 11600, {
    requestId: "TST-CMP-003", requestDate: "2026-07-18", work: "Reforma Administrativa — Obra Teste",
    requester: "Encarregado Teste 03", material: "Tijolos cerâmicos — compra fictícia",
    quantity: 10000, unit: "unidade", neededDate: "2026-07-24", priority: "Alta",
    minimumQuotes: 3, quotesReceived: 3, supplier: "Materiais Exemplo Ltda.", totalAmount: 11600,
    approval: "Aprovada", orderNumber: "PED-TST-003", receivedDate: "2026-07-24",
    receivedQty: 10000, status: "Aprovado", documentsUrl: docs("compra-003"),
  }),

  demo("compliance", "Remuneração mensal — lote fictício", "TST-ESOC-S1200-001", "Validado internamente", "2026-07-01", 0, {
    eventId: "TST-ESOC-S1200-001", eventName: "Remuneração mensal — lote fictício",
    system: "eSocial", eventCode: "S-1200", eventGroup: "Periódico",
    competence: "2026-07-01", environment: "Produção restrita", layoutVersion: "S-1.3",
    companyCnpj: "00.000.000/0001-00", work: "Residencial Horizonte — Obra Teste",
    cno: "00.000.00000/00", ruleSet: "BR-FOLHA-2026.2",
    validationStatus: "Validado internamente", certificateType: "Não configurado",
    payloadHash: "HASH-FICTICIO-NAO-TRANSMITIDO", status: "Validado internamente",
    responsible: "Fiscal Teste",
  }),
  demo("compliance", "Serviços tomados — lote fictício", "TST-REINF-R2010-001", "Aguardando certificado", "2026-07-01", 0, {
    eventId: "TST-REINF-R2010-001", eventName: "Serviços tomados — lote fictício",
    system: "EFD-Reinf", eventCode: "R-2010", eventGroup: "Retenções",
    competence: "2026-07-01", environment: "Produção restrita", layoutVersion: "2.1.2b",
    companyCnpj: "00.000.000/0001-00", work: "Residencial Horizonte — Obra Teste",
    cno: "00.000.00000/00", ruleSet: "REINF-TST-2026.1",
    validationStatus: "Com pendências", certificateType: "Não configurado",
    status: "Aguardando certificado", responsible: "Fiscal Teste",
  }),
  demo("compliance", "Conferência cadastral CNO — fictícia", "TST-CNO-001", "Rascunho", "2026-07-25", 0, {
    eventId: "TST-CNO-001", eventName: "Conferência cadastral CNO — fictícia",
    system: "CNO", eventGroup: "Cadastro de obra", competence: "2026-07-25",
    environment: "Cadastro interno", layoutVersion: "Cadastro Receita Federal",
    companyCnpj: "00.000.000/0001-00", work: "Galpão Industrial Modelo — Obra Teste",
    cno: "11.111.11111/11", validationStatus: "Não iniciada",
    certificateType: "Não configurado", status: "Rascunho", responsible: "Engenharia Teste",
  }),

  demo("rules", "INSS progressivo 2026", "REG-FOLHA-INSS-2026", "Ativa", "2026-01-01", 0, {
    ruleCode: "REG-FOLHA-INSS-2026", name: "INSS progressivo 2026",
    domain: "Folha", sourceBody: "Previdência / Receita Federal",
    sourceUrl: "https://www.gov.br/inss/pt-br/noticias/confira-como-ficaram-as-aliquotas-de-contribuicao-ao-inss",
    scope: "Nacional", region: "Nacional", version: "2026.1", priority: 100,
    validFrom: "2026-01-01", incidence: "Contribuição previdenciária do segurado; cálculo progressivo por faixas.",
    expression: "Aplicar cada alíquota somente à parcela compreendida em sua faixa, respeitando o teto.",
    status: "Ativa", responsible: "Homologação de demonstração",
  }),
  demo("rules", "Leiaute eSocial S-1.3", "REG-ESOC-S13", "Em homologação", "2026-04-27", 0, {
    ruleCode: "REG-ESOC-S13", name: "Leiaute eSocial S-1.3",
    domain: "eSocial", sourceBody: "eSocial",
    sourceUrl: "https://www.gov.br/esocial/pt-br/documentacao-tecnica",
    scope: "Nacional", region: "Nacional", layoutVersion: "S-1.3",
    version: "NT-06-2026", priority: 200, validFrom: "2026-04-27",
    incidence: "Validação de estruturas e regras dos eventos do ambiente nacional.",
    expression: "Validar o XML contra o XSD e as regras do evento antes de liberar a transmissão.",
    status: "Em homologação", responsible: "Compliance Teste",
  }),
  demo("rules", "Convenção coletiva regional — modelo", "REG-CCT-BA-TST", "Rascunho", "2026-05-01", 0, {
    ruleCode: "REG-CCT-BA-TST", name: "Convenção coletiva regional — modelo",
    domain: "Convenção coletiva", sourceBody: "Sindicato / instrumento coletivo a cadastrar",
    scope: "Sindicato", region: "BA", union: "SINDICATO FICTÍCIO — TESTE",
    version: "TST-2026", priority: 300, validFrom: "2026-05-01", validUntil: "2027-04-30",
    incidence: "Pisos, adicionais e benefícios ainda não homologados.",
    expression: "REGRA FICTÍCIA: substituir pelo instrumento coletivo oficial aplicável.",
    status: "Rascunho", responsible: "RH Teste",
  }),

  demo("documents", "Contrato de locação — documento fictício", "TST-DOC-001", "Vigente", "2027-02-28", 0, {
    documentId: "TST-DOC-001", type: "Contrato de locação — documento fictício",
    moduleName: "Imóveis e aluguéis", relatedCode: "TST-IMO-001",
    work: "Residencial Horizonte — Obra Teste", date: "2026-07-01",
    confidentiality: "Restrito à área", validity: "2027-02-28", status: "Vigente",
    responsible: "Administrativo Teste", sharepointUrl: docs("documento-001"), version: "Teste 1.0",
  }),
  demo("documents", "Nota fiscal de materiais — documento fictício", "TST-DOC-002", "Vigente", "2026-12-31", 0, {
    documentId: "TST-DOC-002", type: "Nota fiscal de materiais — documento fictício",
    moduleName: "Compras", relatedCode: "TST-CMP-003", work: "Reforma Administrativa — Obra Teste",
    date: "2026-07-24", confidentiality: "Restrito à área", validity: "2026-12-31",
    status: "Vigente", responsible: "Suprimentos Teste", sharepointUrl: docs("documento-002"),
    version: "Teste 1.0",
  }),
  demo("documents", "Laudo de equipamento — documento fictício", "TST-DOC-003", "Vence em 30 dias", "2026-08-25", 0, {
    documentId: "TST-DOC-003", type: "Laudo de equipamento — documento fictício",
    moduleName: "Máquinas e equipamentos", relatedCode: "TST-ATV-002",
    work: "Residencial Horizonte — Obra Teste", date: "2026-07-20",
    confidentiality: "Geral", validity: "2026-08-25", status: "Vence em 30 dias",
    responsible: "Manutenção Teste", sharepointUrl: docs("documento-003"), version: "Teste 1.0",
  }),

  demo("emails", "financeiro.teste@betaconstrutora.com.br", "financeiro.teste@betaconstrutora.com.br", "Em configuração", "2026-08-03", 0, {
    displayName: "Financeiro Beta — TESTE", email: "financeiro.teste@betaconstrutora.com.br",
    department: "Financeiro", mailboxType: "Caixa compartilhada", license: "Sem licença",
    mfa: "Não aplicável", encryption: "Pendente de configuração", activationDate: "2026-08-03",
    status: "Em configuração", adminOwner: "Equipe de Administração", outlookUrl: "https://outlook.office.com/mail/",
  }),
  demo("emails", "obras.teste@betaconstrutora.com.br", "obras.teste@betaconstrutora.com.br", "Planejada", "2026-08-05", 0, {
    displayName: "Obras Beta — TESTE", email: "obras.teste@betaconstrutora.com.br",
    department: "Operações", mailboxType: "Caixa compartilhada", license: "Sem licença",
    mfa: "Não aplicável", encryption: "Não validado", activationDate: "2026-08-05",
    status: "Planejada", adminOwner: "Equipe de Administração", outlookUrl: "https://outlook.office.com/mail/",
  }),
  demo("emails", "gestor.teste@betaconstrutora.com.br", "gestor.teste@betaconstrutora.com.br", "Ativa", "2026-07-27", 0, {
    displayName: "Gestor Demonstração — TESTE", email: "gestor.teste@betaconstrutora.com.br",
    department: "Gestão", mailboxType: "Usuário individual", license: "Business Basic",
    mfa: "Ativo", encryption: "Política aplicada", activationDate: "2026-07-27",
    status: "Ativa", adminOwner: "Equipe de Administração", outlookUrl: "https://outlook.office.com/mail/",
  }),

  demo("m365", "Equipe Beta Gestão — integração fictícia", "Teams", "Em teste", "2026-07-27", 0, {
    service: "Teams", name: "Equipe Beta Gestão — integração fictícia", owner: "Equipe de Administração",
    status: "Em teste", publishedDate: "2026-07-27", url: docs("teams-teste"),
  }),
  demo("m365", "Central de Documentos — integração fictícia", "SharePoint", "Em teste", "2026-07-27", 0, {
    service: "SharePoint", name: "Central de Documentos — integração fictícia", owner: "Equipe de Administração",
    status: "Em teste", publishedDate: "2026-07-27", url: docs("sharepoint-teste"),
  }),
  demo("m365", "Aprovação de pagamentos — fluxo fictício", "Power Automate", "Planejado", "2026-08-10", 0, {
    service: "Power Automate", name: "Aprovação de pagamentos — fluxo fictício", owner: "Equipe de Administração",
    status: "Planejado", publishedDate: "2026-08-10", url: docs("power-automate-teste"),
  }),
];
